#!/usr/bin/env python3
"""Generate craft / cleanup / path-boolean long-tail SEO tool pages."""
from pathlib import Path

from tool_page_builder import build_page, note, guides

ROOT = Path(__file__).resolve().parent.parent

CLUSTERS = {
    "layout": [
        "/fix-svg-clipping-online",
        "/make-svg-scale-with-container",
        "/make-svg-responsive-online",
    ],
    "export_clean": [
        "/remove-xml-declaration-from-svg",
        "/clean-illustrator-svg-online",
        "/clean-figma-svg-online",
        "/remove-hidden-layers-from-svg",
        "/remove-empty-attributes-from-svg",
        "/remove-data-attributes-from-svg",
    ],
    "style_css": [
        "/strip-inline-styles-from-svg",
        "/change-svg-fill-color-with-css",
        "/convert-svg-colors-to-css-variables",
        "/change-svg-fill-color-on-hover",
        "/make-svg-icon-monochrome-online",
        "/convert-svg-presentation-attributes-to-css",
        "/convert-svg-attributes-to-css-classes",
        "/remove-svg-presentation-attributes",
    ],
    "layout_box": [
        "/fix-svg-stretching-in-flexbox",
        "/prevent-svg-distortion-in-css-grid",
        "/make-svg-responsive-online",
        "/make-svg-scale-with-container",
    ],
    "exporter_ns": [
        "/remove-inkscape-namespaces-from-svg",
        "/remove-sodipodi-attributes-from-svg",
        "/clean-sketch-svg-export-online",
        "/remove-unused-svg-namespaces-online",
        "/clean-illustrator-svg-online",
        "/clean-figma-svg-online",
    ],
    "bbox": [
        "/crop-svg-to-bounding-box",
        "/calculate-svg-bounding-box-online",
        "/crop-svg-online",
        "/calculate-svg-viewbox",
    ],
    "paint_inherit": [
        "/convert-svg-colors-to-currentcolor",
        "/remove-hardcoded-stroke-from-svg",
        "/change-svg-fill-and-stroke-on-hover",
        "/convert-svg-fill-to-currentcolor",
        "/change-svg-fill-color-on-hover",
    ],
    "path_ops": [
        "/bake-svg-transforms-into-path",
        "/convert-svg-stroke-to-path",
        "/skew-svg-path-online",
        "/close-open-svg-paths-online",
        "/merge-svg-paths-online",
        "/offset-svg-path-online",
        "/convert-svg-text-to-path",
        "/split-compound-svg-paths",
        "/ungroup-svg-paths-online",
        "/unite-svg-paths-online",
        "/subtract-svg-paths-online",
        "/intersect-svg-paths-online",
        "/create-compound-svg-path",
        "/convert-svg-arcs-to-cubic-curves",
    ],
}

LABEL = {
    "/fix-svg-clipping-online": "Fix clipping",
    "/make-svg-scale-with-container": "Scale with container",
    "/make-svg-responsive-online": "Make responsive",
    "/remove-xml-declaration-from-svg": "Remove XML declaration",
    "/clean-illustrator-svg-online": "Clean Illustrator SVG",
    "/clean-figma-svg-online": "Clean Figma SVG",
    "/remove-hidden-layers-from-svg": "Remove hidden layers",
    "/remove-empty-attributes-from-svg": "Remove empty attributes",
    "/remove-data-attributes-from-svg": "Remove data attributes",
    "/strip-inline-styles-from-svg": "Strip inline styles",
    "/change-svg-fill-color-with-css": "Fill color with CSS",
    "/convert-svg-colors-to-css-variables": "Colors → CSS variables",
    "/change-svg-fill-color-on-hover": "Fill on hover",
    "/make-svg-icon-monochrome-online": "Monochrome icon",
    "/convert-svg-presentation-attributes-to-css": "Attrs → CSS",
    "/convert-svg-attributes-to-css-classes": "Attrs → classes",
    "/remove-svg-presentation-attributes": "Remove presentation attrs",
    "/bake-svg-transforms-into-path": "Bake transforms",
    "/convert-svg-stroke-to-path": "Stroke to path",
    "/skew-svg-path-online": "Skew path",
    "/close-open-svg-paths-online": "Close open paths",
    "/merge-svg-paths-online": "Merge paths",
    "/offset-svg-path-online": "Offset path",
    "/convert-svg-text-to-path": "Text to path",
    "/split-compound-svg-paths": "Split compound paths",
    "/ungroup-svg-paths-online": "Ungroup paths",
    "/unite-svg-paths-online": "Unite paths",
    "/subtract-svg-paths-online": "Subtract paths",
    "/intersect-svg-paths-online": "Intersect paths",
    "/create-compound-svg-path": "Create compound path",
    "/convert-svg-arcs-to-cubic-curves": "Arcs → cubics",
    "/remove-width-and-height-from-svg": "Remove width/height",
    "/set-svg-preserveaspectratio-online": "preserveAspectRatio",
    "/fix-svg-stretching-in-flexbox": "Fix flexbox stretch",
    "/prevent-svg-distortion-in-css-grid": "Prevent grid distortion",
    "/remove-inkscape-namespaces-from-svg": "Remove Inkscape NS",
    "/remove-sodipodi-attributes-from-svg": "Remove sodipodi attrs",
    "/clean-sketch-svg-export-online": "Clean Sketch SVG",
    "/remove-unused-svg-namespaces-online": "Unused namespaces",
    "/crop-svg-to-bounding-box": "Crop to bounding box",
    "/calculate-svg-bounding-box-online": "Calculate bounding box",
    "/crop-svg-online": "Crop SVG",
    "/calculate-svg-viewbox": "Calculate viewBox",
    "/convert-svg-colors-to-currentcolor": "Colors → currentColor",
    "/remove-hardcoded-stroke-from-svg": "Remove hardcoded stroke",
    "/change-svg-fill-and-stroke-on-hover": "Fill + stroke hover",
    "/convert-svg-fill-to-currentcolor": "Fill → currentColor",
    "/change-svg-fill-color-on-hover": "Fill on hover",
}

FALLBACK = {
    "layout": ["/remove-width-and-height-from-svg", "/set-svg-preserveaspectratio-online"],
}


def cluster_guides(cluster, slug):
    hrefs = [h for h in CLUSTERS[cluster] if h != f"/{slug}"]
    for h in FALLBACK.get(cluster, []):
        if h != f"/{slug}" and h not in hrefs:
            hrefs.append(h)
    return guides([(h, LABEL.get(h, h.strip("/"))) for h in hrefs[:4]])


def cluster_note(cluster, slug):
    hrefs = [h for h in CLUSTERS[cluster] if h != f"/{slug}"]
    for h in FALLBACK.get(cluster, []):
        if h != f"/{slug}" and h not in hrefs:
            hrefs.append(h)
    a, b = hrefs[0], hrefs[1]
    return note(a, LABEL.get(a, a), b, LABEL.get(b, b))


def page(cluster, slug, title, description, h1, crumb, sub, og_alt, app_name, app_alts, app_desc, features, howto_name, howto_desc, howto_click, btn, btn_title, faqs, empty):
    return {
        "family": "craft",
        "cluster": cluster,
        "slug": slug,
        "title": title,
        "description": description,
        "h1": h1,
        "crumb": crumb,
        "sub": sub,
        "og_alt": og_alt,
        "app_name": app_name,
        "app_alts": app_alts,
        "app_desc": app_desc,
        "features": features,
        "howto_name": howto_name,
        "howto_desc": howto_desc,
        "howto_click": howto_click,
        "btn": btn,
        "btn_title": btn_title,
        "faq_aria": f"{h1} FAQ",
        "faqs": faqs,
        "note_html": cluster_note(cluster, slug),
        "guides": cluster_guides(cluster, slug),
        "empty": empty,
    }


PAGES = [
    page(
        "layout", "fix-svg-clipping-online",
        "Fix SVG Clipping Online — Free Tool | getsvgeditor.com",
        "Fix SVG clipping online. Expand a tight clipPath so artwork stops getting cut off — free live preview, no upload.",
        "Fix SVG Clipping Online", "Fix SVG clipping",
        "Repair a <strong>tight clipPath</strong> that crops the graphic — not a viewBox crop",
        "Fix SVG clipping online in SVGEditor",
        "Fix SVG Clipping Online",
        ["Fix SVG clipping online", "Repair SVG clipPath overflow", "SVG clipped artwork fix", "Unclip SVG online"],
        "Free online tool to fix SVG clipping. Expand or remove a clipPath that cuts off shapes.",
        ["Expands tight clipPath", "Keeps viewBox", "Live preview", "No upload"],
        "Fix SVG clipping online",
        "Widen a clipPath that crops visible artwork.",
        "Click Fix clipping. The clipPath box grows to the viewBox so the badge is no longer cropped.",
        "Fix clipping", "Fix SVG clipPath cropping",
        [
            ("How do I fix SVG clipping online when a shape is cut off?", "Paste the clipped SVG and click Fix clipping. A too-small clipPath is expanded to the viewBox so the artwork shows in full."),
            ("Is fix SVG clipping the same as cropping the viewBox?", "No. This pass repairs clipPath / clip-path overflow. Use Crop SVG or Fix viewBox cropping when the canvas itself is wrong."),
            ("Will fixing clipping delete my clipPath?", "Only if there is no usable clip geometry. Otherwise the clip box is enlarged so it no longer hides the graphic."),
            ("Does the sample show clipping before I click?", "Yes. The badge is cut by a small clipPath until you run Fix clipping."),
        ],
        "Paste a clipped SVG. Click Fix clipping to uncrop the artwork.",
    ),
    page(
        "layout", "make-svg-scale-with-container",
        "Make SVG Scale With Container — Free Tool | getsvgeditor.com",
        "Make SVG scale with container. Set width 100% and height auto so the graphic follows its parent — free, no upload.",
        "Make SVG Scale With Container", "Scale with container",
        "Set <code>width:100%</code> and <code>height:auto</code> so the SVG follows the parent box",
        "Make SVG scale with container in SVGEditor",
        "Make SVG Scale With Container",
        ["Make SVG scale with container", "SVG width 100% height auto", "SVG fluid parent size", "Scale SVG to parent"],
        "Free online tool to make an SVG scale with its CSS container using width 100% and height auto.",
        ["width 100% + height auto", "display block", "viewBox kept", "No upload"],
        "Make SVG scale with container",
        "Rewrite root style so the SVG tracks the parent width.",
        "Click Scale with container. Root style becomes width:100%;height:auto;display:block.",
        "Scale with container", "Make this SVG scale with its parent",
        [
            ("How do I make an SVG scale with its container?", "Click Scale with container. The root gets width:100%, height:auto, and display:block so CSS parent width drives size."),
            ("How is scale-with-container different from a responsive SVG?", "Scale-with-container is the CSS size contract (100% / auto). Make SVG Responsive Online adds preserveAspectRatio meet and ensures a viewBox."),
            ("Do I still need a viewBox after scaling with the container?", "Yes. viewBox keeps aspect. This tool does not invent a crop; it only sets fluid CSS size."),
            ("Will fixed width and height attributes fight the container?", "Root width/height attributes are stripped so they cannot override the 100% style."),
        ],
        "Paste a fixed-size SVG. Click Scale with container.",
    ),
    page(
        "layout", "make-svg-responsive-online",
        "Make SVG Responsive Online — Free Tool | getsvgeditor.com",
        "Make SVG responsive online. Keep viewBox, set preserveAspectRatio meet, drop fixed px size — free browser tool.",
        "Make SVG Responsive Online", "Make SVG responsive",
        "Add <code>preserveAspectRatio=\"xMidYMid meet\"</code> and keep viewBox so the SVG stays responsive",
        "Make SVG responsive online in SVGEditor",
        "Make SVG Responsive Online",
        ["Make SVG responsive online", "Responsive SVG viewBox meet", "Fluid SVG without distortion", "SVG responsive markup"],
        "Free online tool to make SVG responsive: viewBox plus preserveAspectRatio meet, no root pixel size.",
        ["Ensures viewBox", "xMidYMid meet", "Strips root px size", "No upload"],
        "Make SVG responsive online",
        "Prepare markup that scales without stretching.",
        "Click Make responsive. viewBox is kept or added, preserveAspectRatio is meet, root px size is removed.",
        "Make responsive", "Make this SVG responsive",
        [
            ("How do I make an SVG responsive online?", "Click Make responsive. The tool keeps or adds viewBox, sets preserveAspectRatio to xMidYMid meet, and removes root pixel width/height."),
            ("Why not only set width 100% for a responsive SVG?", "100% without meet can squash art in a tall or wide box. This page locks aspect via preserveAspectRatio. Use Scale With Container for the CSS 100%/auto pair."),
            ("Does make-responsive change path data?", "No. Only root sizing attributes. Geometry stays put."),
            ("Can I combine responsive SVG with a flex parent?", "Yes. After this pass, drop the SVG in flex/grid. For gradient stretch in flex, use the Flexbox aspect tools."),
        ],
        "Paste a px-sized SVG. Click Make responsive.",
    ),
    page(
        "export_clean", "remove-xml-declaration-from-svg",
        "Remove XML Declaration From SVG — Free Tool | getsvgeditor.com",
        "Remove XML declaration from SVG. Strip <?xml ...?> (and optional doctype) for inline HTML — free, no upload.",
        "Remove XML Declaration From SVG", "Remove XML declaration",
        "Drop the <code>&lt;?xml …?&gt;</code> prolog so the file is safe to inline",
        "Remove XML declaration from SVG in SVGEditor",
        "Remove XML Declaration From SVG",
        ["Remove XML declaration from SVG", "Strip SVG XML prolog", "Delete <?xml from SVG", "SVG without XML header"],
        "Free online tool to remove the XML declaration from SVG markup for HTML inlining.",
        ["Removes <?xml …?>", "Optional doctype strip", "Keeps the svg root", "No upload"],
        "Remove XML declaration from SVG",
        "Delete the XML prolog from SVG source.",
        "Click Remove XML declaration. The <?xml …?> line (and a doctype if present) is deleted.",
        "Remove XML declaration", "Remove the XML declaration from this SVG",
        [
            ("How do I remove the XML declaration from an SVG?", "Paste markup that starts with <?xml and click Remove XML declaration. The prolog is deleted; the <svg> root stays."),
            ("Why remove an XML declaration before inlining SVG in HTML?", "HTML parsers treat <?xml as unexpected. Stripping it avoids quirks when you paste SVG into a page."),
            ("Does this also remove Adobe or Figma junk?", "No. Use Clean Illustrator SVG or Clean Figma SVG for exporter metadata."),
            ("Is the XML declaration required for a valid .svg file?", "Not for browsers. viewBox and xmlns matter more. A standalone file can omit the prolog."),
        ],
        "Paste SVG that starts with <?xml. Click Remove XML declaration.",
    ),
    page(
        "export_clean", "clean-illustrator-svg-online",
        "Clean Illustrator SVG Online — Free Tool | getsvgeditor.com",
        "Clean Illustrator SVG online. Strip i:*, sodipodi, metadata, and Illustrator leftovers — free, no upload.",
        "Clean Illustrator SVG Online", "Clean Illustrator SVG",
        "Remove <strong>Illustrator / Inkscape</strong> namespaces, metadata, and editor-only attributes",
        "Clean Illustrator SVG online in SVGEditor",
        "Clean Illustrator SVG Online",
        ["Clean Illustrator SVG online", "Remove Illustrator SVG metadata", "Strip i: attrs from SVG", "Illustrator SVG cleaner"],
        "Free online tool to clean Illustrator SVG exports: drop editor namespaces and metadata.",
        ["Drops i: / inkscape / sodipodi", "Removes metadata", "Keeps drawable shapes", "No upload"],
        "Clean Illustrator SVG online",
        "Strip Illustrator exporter noise from SVG.",
        "Click Clean Illustrator SVG. Editor namespaces, metadata, and leftover attrs are removed.",
        "Clean Illustrator SVG", "Clean Illustrator leftovers from this SVG",
        [
            ("What does clean Illustrator SVG online remove?", "Illustrator i:* attributes, Inkscape/sodipodi leftovers, metadata, and enable-background — not the visible paths."),
            ("Is this the same as Clean Figma SVG?", "No. Illustrator cleanup targets Adobe/Inkscape namespaces. Figma cleanup targets data-name frames and Figma ids."),
            ("Will colors and path data survive Illustrator cleanup?", "Yes. Paint and geometry stay. Only editor chrome is dropped."),
            ("Should I also remove hidden layers after Illustrator export?", "Often yes. Hidden layers from the Layers panel can still export — use Remove Hidden Layers next."),
        ],
        "Paste an Illustrator export. Click Clean Illustrator SVG.",
    ),
    page(
        "export_clean", "clean-figma-svg-online",
        "Clean Figma SVG Online — Free Tool | getsvgeditor.com",
        "Clean Figma SVG online. Strip data-name frames, Figma ids, and export wrappers — free live preview.",
        "Clean Figma SVG Online", "Clean Figma SVG",
        "Remove <strong>Figma frame names</strong>, data-name, and export wrapper ids",
        "Clean Figma SVG online in SVGEditor",
        "Clean Figma SVG Online",
        ["Clean Figma SVG online", "Remove Figma data-name from SVG", "Figma SVG cleaner", "Strip Figma export ids"],
        "Free online tool to clean Figma SVG exports: drop data-name and frame wrappers noise.",
        ["Removes data-name", "Drops Figma-ish ids", "Keeps vectors", "No upload"],
        "Clean Figma SVG online",
        "Strip Figma export naming from SVG.",
        "Click Clean Figma SVG. data-name, Frame ids, and export-only attributes are removed.",
        "Clean Figma SVG", "Clean Figma leftovers from this SVG",
        [
            ("What does clean Figma SVG online remove?", "data-name, Frame/Group ids from Figma, and empty wrapper attributes. Paths and fills stay."),
            ("Does Figma cleanup convert components to React Native?", "No. This is markup hygiene. Use Figma SVG to React Native if you need RN components."),
            ("Why is clean Figma different from Illustrator cleanup?", "Figma ships data-name and frame ids. Illustrator ships i:* and metadata. Each cleaner targets that exporter."),
            ("Can I ungroup after cleaning a Figma SVG?", "Yes. Ungroup SVG Paths Online unwraps leftover <g> frames once names are gone."),
        ],
        "Paste a Figma SVG export. Click Clean Figma SVG.",
    ),
    page(
        "export_clean", "remove-hidden-layers-from-svg",
        "Remove Hidden Layers From SVG — Free Tool | getsvgeditor.com",
        "Remove hidden layers from SVG. Delete display:none, visibility:hidden, and opacity 0 groups — free, no upload.",
        "Remove Hidden Layers From SVG", "Remove hidden layers",
        "Delete layers with <code>display:none</code>, <code>visibility:hidden</code>, or <code>opacity=\"0\"</code>",
        "Remove hidden layers from SVG in SVGEditor",
        "Remove Hidden Layers From SVG",
        ["Remove hidden layers from SVG", "Delete display none SVG groups", "SVG hidden layer cleaner", "Strip invisible SVG layers"],
        "Free online tool to remove hidden SVG layers that design tools still export.",
        ["Removes display:none", "Removes visibility:hidden", "Drops opacity 0", "No upload"],
        "Remove hidden layers from SVG",
        "Delete invisible exported layers.",
        "Click Remove hidden layers. Hidden groups and shapes are deleted from the tree.",
        "Remove hidden layers", "Remove hidden layers from this SVG",
        [
            ("How do I remove hidden layers from an SVG export?", "Click Remove hidden layers. Elements with display:none, visibility:hidden, hidden, or opacity 0 are deleted."),
            ("Are opacity-0 decorative fades treated as hidden layers?", "This pass treats opacity=\"0\" as hidden. Soft fades with opacity above 0 stay."),
            ("Is a hidden layer the same as an empty group?", "No. Empty groups have no children. Hidden layers have artwork that is turned off — use Remove Empty Groups for hollow wrappers."),
            ("Will clipPath leftovers remain after removing hidden layers?", "Sometimes. Fix SVG Clipping Online if a leftover clip still crops the art."),
        ],
        "Paste SVG with a hidden layer. Click Remove hidden layers.",
    ),
    page(
        "style_css", "strip-inline-styles-from-svg",
        "Strip Inline Styles From SVG — Free Tool | getsvgeditor.com",
        "Strip inline styles from SVG. Remove style=\"…\" attributes without converting them — free, no upload.",
        "Strip Inline Styles From SVG", "Strip inline styles",
        "Delete <code>style=\"…\"</code> attributes outright — not convert them to presentation attrs",
        "Strip inline styles from SVG in SVGEditor",
        "Strip Inline Styles From SVG",
        ["Strip inline styles from SVG", "Remove SVG style attributes", "Delete inline CSS on SVG", "SVG without style="],
        "Free online tool to strip inline style attributes from SVG elements.",
        ["Removes style attributes", "Does not copy to attrs", "Keeps classes / presentation attrs", "No upload"],
        "Strip inline styles from SVG",
        "Drop inline style attributes from the tree.",
        "Click Strip inline styles. Every style=\"…\" attribute is removed.",
        "Strip inline styles", "Strip inline style attributes",
        [
            ("How is strip inline styles different from converting them to attributes?", "Strip deletes style=\"…\". Convert Inline Styles to Presentation Attributes copies fill/stroke into attributes first."),
            ("Will presentation attributes like fill= survive stripping styles?", "Yes. Only the style attribute is removed."),
            ("Does strip inline styles remove <style> blocks?", "No. Use Remove Style Tags From SVG for <style> elements."),
            ("Why strip instead of converting?", "When you want CSS or currentColor to win, leftover inline styles block inheritance."),
        ],
        "Paste SVG with style=\"fill:…\". Click Strip inline styles.",
    ),
    page(
        "style_css", "change-svg-fill-color-with-css",
        "Change SVG Fill Color With CSS — Free Tool | getsvgeditor.com",
        "Change SVG fill color with CSS. Move fills into a class + <style> rule — free live preview, no upload.",
        "Change SVG Fill Color With CSS", "Fill color with CSS",
        "Rewrite hardcoded fills as a <code>.svg-fill</code> class you can theme in CSS",
        "Change SVG fill color with CSS in SVGEditor",
        "Change SVG Fill Color With CSS",
        ["Change SVG fill color with CSS", "SVG fill via CSS class", "Theme SVG fill in stylesheet", "SVG fill CSS rule"],
        "Free online tool to change SVG fill color with CSS classes instead of hardcoded fill attributes.",
        ["Adds a CSS fill class", "Removes hardcoded fill", "Editable <style>", "No upload"],
        "Change SVG fill color with CSS",
        "Move fill paints into a stylesheet class.",
        "Click Apply CSS fill. Shapes get class svg-fill and a <style> rule sets the color.",
        "Apply CSS fill", "Move fills into a CSS class",
        [
            ("How do I change SVG fill color with CSS?", "Click Apply CSS fill. Hardcoded fills become class=\"svg-fill\" and a <style> block sets fill."),
            ("Is this the same as currentColor?", "No. currentColor inherits from CSS color. This page uses an explicit class rule you can edit."),
            ("Can I hover the fill after applying CSS?", "Use Change SVG Fill Color On Hover for a :hover rule. This page only sets the resting fill."),
            ("Do gradient url(#) fills become CSS?", "url() paints stay as attributes so gradient defs keep working."),
        ],
        "Paste a filled icon. Click Apply CSS fill.",
    ),
    page(
        "style_css", "convert-svg-colors-to-css-variables",
        "Convert SVG Colors to CSS Variables — Free Tool | getsvgeditor.com",
        "Convert SVG colors to CSS variables. Replace hex fills with var(--svg-c1) tokens — free, no upload.",
        "Convert SVG Colors to CSS Variables", "Colors → CSS variables",
        "Map hex fills to <code>var(--svg-c1)</code> tokens on the root",
        "Convert SVG colors to CSS variables in SVGEditor",
        "Convert SVG Colors to CSS Variables",
        ["Convert SVG colors to CSS variables", "SVG fill CSS custom properties", "SVG color tokens", "Hex to var(-- ) SVG"],
        "Free online tool to convert SVG hex colors into CSS custom properties.",
        ["Root CSS variables", "fill=var(--svg-cN)", "Unique colors tokenized", "No upload"],
        "Convert SVG colors to CSS variables",
        "Tokenize hex fills as CSS variables.",
        "Click Convert to CSS variables. Each unique hex fill becomes a --svg-cN variable.",
        "Convert to CSS variables", "Convert hex colors to CSS variables",
        [
            ("How do I convert SVG colors to CSS variables?", "Click Convert to CSS variables. Unique hex fills become --svg-c1, --svg-c2 on the root, and shapes use var(--svg-cN)."),
            ("How is this different from a CSS fill class?", "Variables keep multiple colors. A single CSS fill class forces one fill. Use Fill Color With CSS for a one-class theme."),
            ("Can I edit the tokens after conversion?", "Yes. Change --svg-c1 on the root style or in a parent stylesheet."),
            ("Are stroke colors converted too?", "Yes when they are hex/rgb. none and url() paints are left alone."),
        ],
        "Paste a multi-color icon. Click Convert to CSS variables.",
    ),
    page(
        "style_css", "change-svg-fill-color-on-hover",
        "Change SVG Fill Color On Hover — Free Tool | getsvgeditor.com",
        "Change SVG fill color on hover. Add a :hover CSS rule for icon fills — free live preview.",
        "Change SVG Fill Color On Hover", "Fill on hover",
        "Add a <code>:hover</code> fill rule so the icon recolors on pointer hover",
        "Change SVG fill color on hover in SVGEditor",
        "Change SVG Fill Color On Hover",
        ["Change SVG fill color on hover", "SVG icon hover fill CSS", "SVG :hover fill", "Hover color for SVG"],
        "Free online tool to change SVG fill color on hover with a CSS :hover rule.",
        [":hover fill rule", "Resting fill class", "Inline <style>", "No upload"],
        "Change SVG fill color on hover",
        "Attach a hover fill stylesheet to the SVG.",
        "Click Apply hover fill. A .svg-hover-fill:hover rule switches the fill color.",
        "Apply hover fill", "Add a CSS hover fill",
        [
            ("How do I change SVG fill color on hover?", "Click Apply hover fill. Shapes get class svg-hover-fill and a :hover rule in <style> changes the fill."),
            ("Why doesn’t hover work on an <img src=…svg>?", "Hover CSS inside the file does not apply through <img>. Inline the SVG (or an object) so :hover can reach the paths."),
            ("Is hover fill the same as CSS variables?", "No. Hover adds a pointer state. Variables tokenize the palette. Combine them if you want both."),
            ("Can I pick the hover color in Source?", "Yes. Edit the :hover fill in the generated <style> block."),
        ],
        "Paste an icon. Click Apply hover fill, then hover the preview.",
    ),
    page(
        "style_css", "make-svg-icon-monochrome-online",
        "Make SVG Icon Monochrome Online — Free Tool | getsvgeditor.com",
        "Make SVG icon monochrome online. Flatten multi-color fills to one currentColor — free, no upload.",
        "Make SVG Icon Monochrome Online", "Monochrome icon",
        "Flatten multi-color fills to a single <code>currentColor</code> ink",
        "Make SVG icon monochrome online in SVGEditor",
        "Make SVG Icon Monochrome Online",
        ["Make SVG icon monochrome online", "Single color SVG icon", "Flatten SVG to one fill", "Monochrome SVG converter"],
        "Free online tool to make an SVG icon monochrome with one inheritable fill.",
        ["One currentColor fill", "Keeps none / strokes optional", "Icon-ready", "No upload"],
        "Make SVG icon monochrome online",
        "Collapse the palette to one ink.",
        "Click Make monochrome. Colored fills become currentColor for a one-ink icon.",
        "Make monochrome", "Flatten this icon to one color",
        [
            ("How do I make an SVG icon monochrome online?", "Click Make monochrome. Distinct hex fills become currentColor so CSS color sets the ink."),
            ("How is monochrome different from fill → currentColor on a few paths?", "Monochrome is the icon intent: every solid fill (and typical stroke) becomes one ink. The currentColor style page is a fill-only rewrite."),
            ("Do holes and fill=none stay open?", "Yes. fill=\"none\" is kept so compound icons do not flood."),
            ("Can I recolor the monochrome icon in CSS?", "Yes. Set color on the parent. The icon inherits through currentColor."),
        ],
        "Paste a multi-color icon. Click Make monochrome.",
    ),
    page(
        "style_css", "convert-svg-presentation-attributes-to-css",
        "Convert SVG Presentation Attributes to CSS — Free Tool | getsvgeditor.com",
        "Convert SVG presentation attributes to CSS. Move fill/stroke into a <style> block — not inline style attributes.",
        "Convert SVG Presentation Attributes to CSS", "Attrs → CSS",
        "Move fill/stroke into a <code>&lt;style&gt;</code> rule — not inline <code>style=\"\"</code>",
        "Convert SVG presentation attributes to CSS in SVGEditor",
        "Convert SVG Presentation Attributes to CSS",
        ["Convert SVG presentation attributes to CSS", "SVG attrs to stylesheet", "fill stroke into CSS", "Presentation attrs to CSS"],
        "Free online tool to convert SVG presentation attributes into a CSS stylesheet block.",
        ["<style> rules from attrs", "Classes on shapes", "Not inline style=", "No upload"],
        "Convert SVG presentation attributes to CSS",
        "Lift presentation attributes into CSS rules.",
        "Click Convert attrs to CSS. fill/stroke become classes plus a <style> block.",
        "Convert attrs to CSS", "Convert presentation attributes to CSS",
        [
            ("How do presentation attributes become CSS (not inline styles)?", "Click Convert attrs to CSS. Shared fill/stroke values become classes and a <style> block — not style=\"fill:…\" on each node."),
            ("Where is convert attributes to inline styles?", "That is Convert Presentation Attributes to Inline Styles — a different page that writes style=\"\"."),
            ("Will convert-to-CSS keep unique colors?", "Yes. Each unique fill/stroke pair gets its own class."),
            ("Can I turn those classes back into attributes later?", "Yes. Convert SVG CSS Classes to Attributes applies the stylesheet back onto elements."),
        ],
        "Paste SVG with fill= attributes. Click Convert attrs to CSS.",
    ),
    page(
        "style_css", "convert-svg-attributes-to-css-classes",
        "Convert SVG Attributes to CSS Classes — Free Tool | getsvgeditor.com",
        "Convert SVG attributes to CSS classes. Group identical fill/stroke into shared class names — free, no upload.",
        "Convert SVG Attributes to CSS Classes", "Attrs → classes",
        "Group identical fill/stroke pairs into <strong>shared class names</strong>",
        "Convert SVG attributes to CSS classes in SVGEditor",
        "Convert SVG Attributes to CSS Classes",
        ["Convert SVG attributes to CSS classes", "SVG shared fill classes", "Deduplicate SVG styles", "Attributes to class names"],
        "Free online tool to convert repeated SVG presentation attributes into shared CSS classes.",
        ["Dedupes identical paints", "Shared class names", "Stylesheet generated", "No upload"],
        "Convert SVG attributes to CSS classes",
        "Collapse repeated paints into classes.",
        "Click Convert to CSS classes. Identical fill/stroke pairs share one class.",
        "Convert to CSS classes", "Convert attributes to shared CSS classes",
        [
            ("How do SVG attributes become shared CSS classes?", "Click Convert to CSS classes. Shapes with the same fill/stroke share a class; the rule lives in <style>."),
            ("How is this different from attrs → CSS on unique shapes?", "Attrs → CSS always emits classes. This page stresses sharing: two blue rects become one class, not two."),
            ("Does converting to classes change geometry?", "No. Only paint attributes move into CSS."),
            ("Can I strip leftover presentation attributes after classing?", "The convert pass already removes the moved fill/stroke attributes from the elements."),
        ],
        "Paste SVG with repeated fills. Click Convert to CSS classes.",
    ),
    page(
        "style_css", "remove-svg-presentation-attributes",
        "Remove SVG Presentation Attributes — Free Tool | getsvgeditor.com",
        "Remove SVG presentation attributes. Drop fill, stroke, opacity attrs without adding CSS — free, no upload.",
        "Remove SVG Presentation Attributes", "Remove presentation attrs",
        "Delete fill/stroke/opacity attributes — no CSS rewrite, inheritance takes over",
        "Remove SVG presentation attributes in SVGEditor",
        "Remove SVG Presentation Attributes",
        ["Remove SVG presentation attributes", "Delete SVG fill stroke attrs", "Strip presentation attrs", "SVG without fill attributes"],
        "Free online tool to remove SVG presentation attributes so CSS inheritance can win.",
        ["Removes fill/stroke/opacity attrs", "Does not add CSS", "Keeps d / geometry", "No upload"],
        "Remove SVG presentation attributes",
        "Delete presentation attributes from elements.",
        "Click Remove presentation attrs. fill, stroke, and related attrs are deleted.",
        "Remove presentation attrs", "Remove presentation attributes",
        [
            ("What happens when I remove SVG presentation attributes?", "fill, stroke, opacity, and other presentation attrs are deleted. Geometry (d, cx, points) stays. CSS or UA defaults then paint the shape."),
            ("Is this the same as converting attributes to CSS?", "No. Convert-to-CSS keeps the look in a stylesheet. Remove means the attributes are gone."),
            ("Will the icon disappear after removing fills?", "It may fall back to black or inherit. Add CSS or currentColor if you still need a fill."),
            ("Are style=\"\" attributes removed too?", "This pass targets presentation attributes. Use Strip Inline Styles for style=\"\"."),
        ],
        "Paste a filled shape. Click Remove presentation attrs.",
    ),
    page(
        "export_clean", "remove-empty-attributes-from-svg",
        "Remove Empty Attributes From SVG — Free Tool | getsvgeditor.com",
        "Remove empty attributes from SVG. Delete id=\"\", class=\"\", and other empty attr values — free, no upload.",
        "Remove Empty Attributes From SVG", "Remove empty attributes",
        "Delete attributes whose value is <strong>empty</strong> (<code>id=\"\"</code>, <code>class=\"\"</code>)",
        "Remove empty attributes from SVG in SVGEditor",
        "Remove Empty Attributes From SVG",
        ["Remove empty attributes from SVG", "Delete empty SVG attrs", "SVG empty attribute cleaner", "Strip blank SVG attributes"],
        "Free online tool to remove empty attributes from SVG markup.",
        ["Drops empty values", "Keeps meaningful attrs", "Live preview", "No upload"],
        "Remove empty attributes from SVG",
        "Delete attributes with blank values.",
        "Click Remove empty attributes. Attributes with empty strings are removed.",
        "Remove empty attributes", "Remove empty attributes from this SVG",
        [
            ("Which empty attributes get removed from SVG?", "Any attribute whose value is \"\" or only whitespace — id, class, data-*, and others."),
            ("Is an empty attribute the same as a data- attribute?", "No. Empty means blank value. Remove Data Attributes deletes every data-* key, even when it has a value."),
            ("Do empty presentation attributes like stroke=\"\" count?", "Yes. Blank stroke/fill attributes are removed."),
            ("Will xmlns stay when I remove empty attributes?", "Yes. xmlns has a real value and is kept."),
        ],
        "Paste SVG with id=\"\". Click Remove empty attributes.",
    ),
    page(
        "export_clean", "remove-data-attributes-from-svg",
        "Remove Data Attributes From SVG — Free Tool | getsvgeditor.com",
        "Remove data attributes from SVG. Strip data-* keys from the tree — free browser tool, no upload.",
        "Remove Data Attributes From SVG", "Remove data attributes",
        "Strip every <code>data-*</code> attribute, including valued ones",
        "Remove data attributes from SVG in SVGEditor",
        "Remove Data Attributes From SVG",
        ["Remove data attributes from SVG", "Strip data-* from SVG", "Delete SVG data attributes", "SVG without data-name"],
        "Free online tool to remove data-* attributes from SVG elements.",
        ["Removes all data-*", "Keeps ids and classes", "Works with Figma leftovers", "No upload"],
        "Remove data attributes from SVG",
        "Delete data-* attributes from the tree.",
        "Click Remove data attributes. Every data-* key is removed.",
        "Remove data attributes", "Remove data-* attributes",
        [
            ("How do I remove data attributes from an SVG?", "Click Remove data attributes. data-name, data-id, and other data-* keys are deleted."),
            ("Should I clean Figma first or only strip data- attributes?", "Figma cleanup also drops frame ids. This page only removes data-*. Use both if the export is noisy."),
            ("Are aria-* or xmlns:xlink removed?", "No. Only attributes that start with data-."),
            ("Do empty data- attributes need a separate pass?", "This pass already deletes them. Empty-attribute cleanup is for blank non-data attrs."),
        ],
        "Paste SVG with data-name. Click Remove data attributes.",
    ),
    page(
        "path_ops", "bake-svg-transforms-into-path",
        "Bake SVG Transforms Into Path — Free Tool | getsvgeditor.com",
        "Bake SVG transforms into path. Flatten translate/rotate/skew into d — free live preview, no upload.",
        "Bake SVG Transforms Into Path", "Bake transforms",
        "Flatten <code>transform=</code> into path <code>d</code> so the matrix is gone",
        "Bake SVG transforms into path in SVGEditor",
        "Bake SVG Transforms Into Path",
        ["Bake SVG transforms into path", "Flatten SVG transform to d", "Apply transform to path data", "SVG bake matrix"],
        "Free online tool to bake SVG transforms into path data.",
        ["Applies matrix to d", "Removes transform attr", "Keeps visual pose", "No upload"],
        "Bake SVG transforms into path",
        "Apply transform matrices onto path commands.",
        "Click Bake transforms. Path coordinates absorb the matrix; transform is removed.",
        "Bake transforms", "Bake transforms into path data",
        [
            ("How do I bake SVG transforms into a path?", "Click Bake transforms. translate/rotate/skew/scale on a path are applied to d and the transform attribute is removed."),
            ("Is bake different from skew SVG path?", "Skew adds a new skewX. Bake consumes an existing transform. Run skew, then bake if you want raw d."),
            ("Do groups with transform get baked?", "Group transforms are applied to descendant paths when possible, then the group transform is cleared."),
            ("Are arc commands baked as cubics?", "Arcs are converted to cubics during bake so the matrix can be applied to Bézier points."),
        ],
        "Paste a path with transform=. Click Bake transforms.",
    ),
    page(
        "path_ops", "convert-svg-stroke-to-path",
        "Convert SVG Stroke to Path — Free Tool | getsvgeditor.com",
        "Convert SVG stroke to path. Outline a stroke into a filled path — free live preview, no upload.",
        "Convert SVG Stroke to Path", "Stroke to path",
        "Turn a stroked outline into a <strong>filled path</strong> (outline stroke)",
        "Convert SVG stroke to path in SVGEditor",
        "Convert SVG Stroke to Path",
        ["Convert SVG stroke to path", "Outline SVG stroke", "Stroke to filled path", "SVG stroke outline online"],
        "Free online tool to convert an SVG stroke into a filled path outline.",
        ["Outlines the stroke", "fill-rule evenodd", "Removes stroke paint", "No upload"],
        "Convert SVG stroke to path",
        "Replace a stroke with an outlined filled path.",
        "Click Stroke to path. The stroke becomes a filled outline path.",
        "Stroke to path", "Convert stroke to a filled path",
        [
            ("How do I convert an SVG stroke to a path?", "Click Stroke to path. The stroked shape is outlined into a filled path (evenodd) and stroke attributes are removed."),
            ("Is stroke-to-path the same as offset path?", "No. Offset shifts or expands a centerline. Stroke-to-path builds a ribbon that matches the stroke width."),
            ("Will dashed strokes stay dashed?", "This pass outlines the solid stroke geometry of the sample. Complex dash patterns may need a design tool."),
            ("Can I merge the new outline with another path?", "Yes. Use Merge or Unite after the outline exists."),
        ],
        "Paste a stroked shape. Click Stroke to path.",
    ),
    page(
        "path_ops", "skew-svg-path-online",
        "Skew SVG Path Online — Free Tool | getsvgeditor.com",
        "Skew SVG path online. Apply skewX to path data and bake it — free live preview, no upload.",
        "Skew SVG Path Online", "Skew path",
        "Apply a <strong>skewX</strong> shear and bake it into <code>d</code>",
        "Skew SVG path online in SVGEditor",
        "Skew SVG Path Online",
        ["Skew SVG path online", "Shear SVG path", "skewX path online", "Slant SVG path"],
        "Free online tool to skew an SVG path (shear) and bake the result into d.",
        ["Applies skewX", "Bakes into d", "Live preview", "No upload"],
        "Skew SVG path online",
        "Shear path coordinates with skewX.",
        "Click Skew path. A skewX shear is baked into the path data.",
        "Skew path", "Skew this SVG path",
        [
            ("How do I skew an SVG path online?", "Click Skew path. A horizontal shear (skewX) is applied and baked into d so no transform remains."),
            ("Can I bake a transform I already wrote?", "Yes — use Bake SVG Transforms Into Path for an existing transform= attribute."),
            ("Does skew change the viewBox?", "No. Only path points move. If the shear clips, Fix SVG Clipping or widen viewBox."),
            ("Is skew the same as rotate?", "No. Skew shears axes; rotate turns around a point. Use the rotate tools for angles."),
        ],
        "Paste a path. Click Skew path to shear it.",
    ),
    page(
        "path_ops", "close-open-svg-paths-online",
        "Close Open SVG Paths Online — Free Tool | getsvgeditor.com",
        "Close open SVG paths online. Append Z to open subpaths — free live preview, no upload.",
        "Close Open SVG Paths Online", "Close open paths",
        "Append <code>Z</code> so open subpaths become closed shapes",
        "Close open SVG paths online in SVGEditor",
        "Close Open SVG Paths Online",
        ["Close open SVG paths online", "Add Z to SVG path", "Close SVG subpath", "Seal open path"],
        "Free online tool to close open SVG paths by appending Z.",
        ["Adds Z to open subpaths", "Skips already-closed paths", "Keeps commands", "No upload"],
        "Close open SVG paths online",
        "Seal open path data with Z.",
        "Click Close open paths. Subpaths that lack Z get a close command.",
        "Close open paths", "Close open SVG paths",
        [
            ("How do I close open SVG paths online?", "Click Close open paths. Each subpath that does not end with Z/z gets a close command."),
            ("Will a closed path be closed twice?", "No. Subpaths that already end with Z are left alone."),
            ("Why close a path before filling?", "Open paths can render with a missing edge. Z makes the fill and stroke join the start point."),
            ("Is this a boolean union?", "No. Closing does not merge shapes. Use Unite or Merge for multiple paths."),
        ],
        "Paste an open path (no Z). Click Close open paths.",
    ),
    page(
        "path_ops", "merge-svg-paths-online",
        "Merge SVG Paths Online — Free Tool | getsvgeditor.com",
        "Merge SVG paths online. Concatenate multiple path d values into one element — not a boolean union.",
        "Merge SVG Paths Online", "Merge paths",
        "Concatenate several <code>d</code> strings into <strong>one path element</strong>",
        "Merge SVG paths online in SVGEditor",
        "Merge SVG Paths Online",
        ["Merge SVG paths online", "Combine SVG path data", "Join path d attributes", "One path from many"],
        "Free online tool to merge SVG paths by concatenating d into one element.",
        ["Joins d strings", "One path node", "Not boolean union", "No upload"],
        "Merge SVG paths online",
        "Concatenate path data into a single path.",
        "Click Merge paths. All path d values are joined into one path element.",
        "Merge paths", "Merge SVG paths into one",
        [
            ("How do I merge SVG paths online?", "Click Merge paths. Every path’s d is concatenated into one <path>. Extra path nodes are removed."),
            ("Is merge the same as unite?", "No. Merge only joins markup. Unite sets fill-rule evenodd as a boolean-style compound. Use Unite when you want one evenodd silhouette."),
            ("Do fills of merged paths stay separate colors?", "The first path’s fill is kept. Convert colors to variables first if you need tokens."),
            ("Can I split the merge later?", "Yes. Split Compound SVG Paths cuts on each M command."),
        ],
        "Paste two paths. Click Merge paths.",
    ),
    page(
        "path_ops", "offset-svg-path-online",
        "Offset SVG Path Online — Free Tool | getsvgeditor.com",
        "Offset SVG path online. Expand a path outward from its center — free live preview, no upload.",
        "Offset SVG Path Online", "Offset path",
        "Expand the path <strong>outward from its center</strong> (simple offset)",
        "Offset SVG path online in SVGEditor",
        "Offset SVG Path Online",
        ["Offset SVG path online", "Expand SVG path", "Path outset online", "Grow SVG path"],
        "Free online tool to offset (outset) an SVG path from its center.",
        ["Outset from center", "Keeps shape family", "Live preview", "No upload"],
        "Offset SVG path online",
        "Scale the path out from its bounding-box center.",
        "Click Offset path. The path is scaled out from center as a simple outset.",
        "Offset path", "Offset this SVG path",
        [
            ("How do I offset an SVG path online?", "Click Offset path. The path is scaled out from its bounding-box center — a simple outset, not a full parallel-curve engine."),
            ("Is offset the same as stroke-to-path?", "No. Offset grows the centerline. Stroke-to-path builds a ribbon of stroke width."),
            ("Will a sharp corner stay sharp after offset?", "This outset preserves the command types. True parallel offsets of sharp corners need a dedicated CAD offset."),
            ("Can I inset instead of outset?", "Edit the factor in Source after a bake, or scale down. This button applies a positive outset."),
        ],
        "Paste a path. Click Offset path to expand it.",
    ),
    page(
        "path_ops", "convert-svg-text-to-path",
        "Convert SVG Text to Path — Free Tool | getsvgeditor.com",
        "Convert SVG text to path. Replace <text> with outlined path data — free live preview, no upload.",
        "Convert SVG Text to Path", "Text to path",
        "Replace <code>&lt;text&gt;</code> with an outlined <code>path</code> so fonts are not required",
        "Convert SVG text to path in SVGEditor",
        "Convert SVG Text to Path",
        ["Convert SVG text to path", "Outline SVG text", "SVG text to vector path", "Fontless SVG letter"],
        "Free online tool to convert SVG text elements into outlined paths.",
        ["Replaces <text>", "Outlined letter path", "No font dependency", "No upload"],
        "Convert SVG text to path",
        "Swap text nodes for outlined paths.",
        "Click Text to path. The sample letter becomes a path outline.",
        "Text to path", "Convert SVG text to a path",
        [
            ("How do I convert SVG text to a path?", "Click Text to path. Each <text> node is replaced with an outlined path so the glyph no longer needs the font file."),
            ("Will my custom font match the outline exactly?", "The sample uses a built-in letter outline. For production fonts, export outlines from the design tool, then paste here to clean."),
            ("Is text-to-path the same as stroke-to-path?", "No. Text-to-path outlines glyphs. Stroke-to-path outlines a stroke."),
            ("Can I merge letter paths after conversion?", "Yes. Merge or Create Compound Path after the letters are paths."),
        ],
        "Paste SVG with <text>. Click Text to path.",
    ),
    page(
        "path_ops", "split-compound-svg-paths",
        "Split Compound SVG Paths — Free Tool | getsvgeditor.com",
        "Split compound SVG paths. Break one d with multiple M commands into separate paths — free, no upload.",
        "Split Compound SVG Paths", "Split compound paths",
        "Break one <code>d</code> with several <code>M</code> subpaths into separate <code>path</code> elements",
        "Split compound SVG paths in SVGEditor",
        "Split Compound SVG Paths",
        ["Split compound SVG paths", "Separate SVG subpaths", "Explode compound path", "Uncompound SVG path"],
        "Free online tool to split a compound SVG path into one element per subpath.",
        ["Absolute subpaths", "One path per M", "Keeps fill", "No upload"],
        "Split compound SVG paths",
        "Explode compound path data into siblings.",
        "Click Split compound. Each drawable M subpath becomes its own path element (relative commands are absolutized).",
        "Split compound", "Split compound SVG paths",
        [
            ("How do I split compound SVG paths?", "Click Split compound. Each drawable M… subpath becomes its own <path>. Relative commands are converted to absolute so positions stay put."),
            ("Is split the inverse of create compound path?", "Yes. Create Compound Path joins siblings; split takes them apart again."),
            ("Do holes stay holes after a split?", "A hole becomes its own path. Re-apply evenodd via Create Compound Path if you need the hole back."),
            ("Will groups be ungrouped by split?", "No. Split only explodes d. Use Ungroup SVG Paths for <g> wrappers."),
        ],
        "Paste a compound path (two M). Click Split compound.",
    ),
    page(
        "path_ops", "ungroup-svg-paths-online",
        "Ungroup SVG Paths Online — Free Tool | getsvgeditor.com",
        "Ungroup SVG paths online. Lift path children out of <g> wrappers — free live preview, no upload.",
        "Ungroup SVG Paths Online", "Ungroup paths",
        "Lift paths out of <code>&lt;g&gt;</code> wrappers (flatten one group level)",
        "Ungroup SVG paths online in SVGEditor",
        "Ungroup SVG Paths Online",
        ["Ungroup SVG paths online", "Flatten SVG groups", "Remove g around paths", "Ungroup SVG layers"],
        "Free online tool to ungroup SVG paths from g wrappers.",
        ["Flattens g children", "Keeps path nodes", "One level per click", "No upload"],
        "Ungroup SVG paths online",
        "Move grouped paths up to the parent.",
        "Click Ungroup paths. Children of <g> are lifted to the parent and empty groups drop.",
        "Ungroup paths", "Ungroup SVG path groups",
        [
            ("How do I ungroup SVG paths online?", "Click Ungroup paths. Children inside <g> move to the parent; empty groups are removed."),
            ("Is ungroup the same as remove empty groups?", "No. Empty-group cleanup deletes hollow g tags. Ungroup moves real children out first."),
            ("Do group transforms survive ungroup?", "A group transform is copied onto children when present, then the wrapper is removed. Bake if you need it in d."),
            ("Can I ungroup Figma frames after cleaning names?", "Yes. Clean Figma SVG, then ungroup leftover Frame groups."),
        ],
        "Paste grouped paths. Click Ungroup paths.",
    ),
    page(
        "path_ops", "unite-svg-paths-online",
        "Unite SVG Paths Online — Free Tool | getsvgeditor.com",
        "Unite SVG paths online. Join shapes into one solid silhouette (fill-rule nonzero) — free, no upload.",
        "Unite SVG Paths Online", "Unite paths",
        "Join shapes into one <strong>solid compound</strong> silhouette (overlap stays filled)",
        "Unite SVG paths online in SVGEditor",
        "Unite SVG Paths Online",
        ["Unite SVG paths online", "Boolean union SVG", "Combine SVG silhouettes", "SVG path union"],
        "Free online tool to unite SVG paths into one solid compound path.",
        ["One compound path", "fill-rule nonzero", "Overlap stays filled", "No upload"],
        "Unite SVG paths online",
        "Combine path silhouettes into one nonzero path.",
        "Click Unite paths. Path data is joined and fill-rule is nonzero so the overlap stays solid.",
        "Unite paths", "Unite SVG paths",
        [
            ("How do I unite SVG paths online?", "Click Unite paths. Path d values are joined into one element with fill-rule nonzero — overlapping areas stay filled like a union."),
            ("How is unite different from merge?", "Merge only concatenates markup. Unite also sets nonzero so the joined silhouette reads as one solid shape."),
            ("Why not evenodd for unite?", "evenodd punches a hole in the overlap. Subtract and Create Compound Path use evenodd for holes; unite keeps the fill."),
            ("When should I subtract instead of unite?", "Use Subtract when the second shape should cut a hole, not add area."),
        ],
        "Paste overlapping paths. Click Unite paths.",
    ),
    page(
        "path_ops", "subtract-svg-paths-online",
        "Subtract SVG Paths Online — Free Tool | getsvgeditor.com",
        "Subtract SVG paths online. Cut the second path out of the first with evenodd — free live preview.",
        "Subtract SVG Paths Online", "Subtract paths",
        "Cut the <strong>second path</strong> out of the first (evenodd hole)",
        "Subtract SVG paths online in SVGEditor",
        "Subtract SVG Paths Online",
        ["Subtract SVG paths online", "SVG path difference", "Cut hole in SVG path", "Boolean subtract SVG"],
        "Free online tool to subtract one SVG path from another using evenodd.",
        ["Second path as hole", "fill-rule evenodd", "One compound path", "No upload"],
        "Subtract SVG paths online",
        "Use the second path as a hole in the first.",
        "Click Subtract paths. The second path becomes a hole in the first via evenodd.",
        "Subtract paths", "Subtract the second path",
        [
            ("How do I subtract SVG paths online?", "Click Subtract paths. The first path is the base; the second is appended as a hole with fill-rule evenodd."),
            ("What if I have more than two paths?", "The first stays the base; remaining paths are appended as cutters."),
            ("Is subtract the opposite of unite?", "Unite adds area into one silhouette. Subtract punches holes. Intersect keeps only overlap."),
            ("Why is the hole not visible?", "Both subpaths must be closed (Z). Close Open Paths first if a cutter is open."),
        ],
        "Paste a moon (circle minus circle). Click Subtract paths.",
    ),
    page(
        "path_ops", "intersect-svg-paths-online",
        "Intersect SVG Paths Online — Free Tool | getsvgeditor.com",
        "Intersect SVG paths online. Keep the overlap using a clipPath from the second shape — free, no upload.",
        "Intersect SVG Paths Online", "Intersect paths",
        "Keep only the <strong>overlap</strong> — clip the first path with the second",
        "Intersect SVG paths online in SVGEditor",
        "Intersect SVG Paths Online",
        ["Intersect SVG paths online", "SVG path intersection", "Boolean intersect SVG", "Keep SVG overlap"],
        "Free online tool to intersect SVG paths by clipping the first with the second.",
        ["clipPath from path 2", "Shows overlap", "Keeps first fill", "No upload"],
        "Intersect SVG paths online",
        "Clip the first path to the second path’s silhouette.",
        "Click Intersect paths. The first path is clipped to the second shape.",
        "Intersect paths", "Intersect SVG paths",
        [
            ("How do I intersect SVG paths online?", "Click Intersect paths. The second path becomes a clipPath; the first path is clipped to that overlap."),
            ("Why clipPath instead of a new Bézier?", "Clip shows the intersection immediately without a full boolean kernel. For a baked outline, export and trace later."),
            ("How is intersect different from fix clipping?", "Fix clipping enlarges a bad clip. Intersect creates a clip on purpose to keep overlap."),
            ("Can I remove the clip after inspecting overlap?", "Yes. Delete the clip-path attribute in Source, or Fix Clipping to widen it."),
        ],
        "Paste two overlapping shapes. Click Intersect paths.",
    ),
    page(
        "path_ops", "create-compound-svg-path",
        "Create Compound SVG Path — Free Tool | getsvgeditor.com",
        "Create compound SVG path. Join sibling paths into one evenodd compound — free, no upload.",
        "Create Compound SVG Path", "Create compound path",
        "Join sibling paths into one <code>d</code> with <code>fill-rule=\"evenodd\"</code>",
        "Create compound SVG path in SVGEditor",
        "Create Compound SVG Path",
        ["Create compound SVG path", "Make compound path SVG", "evenodd compound path", "Join paths compound"],
        "Free online tool to create a compound SVG path from sibling path elements.",
        ["Joins sibling paths", "evenodd compound", "Icon holes ready", "No upload"],
        "Create compound SVG path",
        "Build one evenodd compound from siblings.",
        "Click Create compound. Sibling paths become one evenodd path.",
        "Create compound", "Create a compound SVG path",
        [
            ("How do I create a compound SVG path?", "Click Create compound. Sibling <path> elements are joined into one d with fill-rule evenodd — the usual icon-hole setup."),
            ("How is create-compound different from unite?", "Same family of result; Unite is the boolean-worded action. Create Compound is the Illustrator-style name for joining siblings."),
            ("How do I undo a compound path?", "Use Split Compound SVG Paths to explode on M."),
            ("Should holes be drawn opposite winding?", "evenodd does not require opposite winding. nonzero would; this tool uses evenodd."),
        ],
        "Paste two sibling paths. Click Create compound.",
    ),
    page(
        "path_ops", "convert-svg-arcs-to-cubic-curves",
        "Convert SVG Arcs to Cubic Curves — Free Tool | getsvgeditor.com",
        "Convert SVG arcs to cubic curves. Rewrite A commands as C Béziers — free live preview, no upload.",
        "Convert SVG Arcs to Cubic Curves", "Arcs → cubics",
        "Rewrite <code>A</code> arc commands as cubic <code>C</code> Béziers",
        "Convert SVG arcs to cubic curves in SVGEditor",
        "Convert SVG Arcs to Cubic Curves",
        ["Convert SVG arcs to cubic curves", "SVG A to C commands", "Arc to Bézier SVG", "Flatten SVG arcs"],
        "Free online tool to convert SVG elliptical arc commands into cubic Bézier curves.",
        ["A → C cubics", "Keeps the curve look", "Easier to bake/offset", "No upload"],
        "Convert SVG arcs to cubic curves",
        "Replace arc commands with cubic Béziers.",
        "Click Convert arcs. A commands become C cubics.",
        "Convert arcs", "Convert SVG arcs to cubics",
        [
            ("How do I convert SVG arcs to cubic curves?", "Click Convert arcs. Each A/a command is approximated with cubic C segments."),
            ("Why convert arcs before baking transforms?", "Matrices apply cleanly to Bézier points. Raw arcs need extra ellipse math — bake already converts them."),
            ("Will the arc look identical as cubics?", "Very close. Elliptical arcs are approximated with standard cubic segments."),
            ("Do H/V/L commands change?", "No. Only A/a is rewritten."),
        ],
        "Paste a path with A arcs. Click Convert arcs.",
    ),
    page(
        "layout_box", "fix-svg-stretching-in-flexbox",
        "Fix SVG Stretching in Flexbox — Free Tool | getsvgeditor.com",
        "Fix SVG stretching in flexbox. Set meet + flex-shrink 0 so a flex item stops squashing — free, no upload.",
        "Fix SVG Stretching in Flexbox", "Fix flexbox stretch",
        "Stop a flex item from <strong>stretching the SVG</strong> — meet + flex-shrink:0, not a gradientUnits fix",
        "Fix SVG stretching in flexbox in SVGEditor",
        "Fix SVG Stretching in Flexbox",
        ["Fix SVG stretching in flexbox", "SVG flex item squash fix", "Stop SVG stretch in flex", "Flexbox SVG aspect lock"],
        "Free online tool to fix SVG stretching in flexbox with preserveAspectRatio meet and flex-shrink 0.",
        ["xMidYMid meet", "flex-shrink:0", "height:auto", "No upload"],
        "Fix SVG stretching in flexbox",
        "Rewrite root style so a flex child keeps aspect.",
        "Click Fix flexbox stretch. preserveAspectRatio becomes meet and root style adds flex-shrink:0; height:auto.",
        "Fix flexbox stretch", "Stop this SVG stretching in flexbox",
        [
            ("Why does my SVG stretch inside a flexbox row?", "Flex default align-items:stretch can squash a replaced SVG. This pass sets meet and flex-shrink:0 so the graphic keeps its aspect."),
            ("Is this the same as fix SVG gradient stretch in flexbox?", "No. Gradient stretch is gradientUnits=objectBoundingBox. This page fixes the SVG box itself stretching as a flex item."),
            ("Do I still need width 100% after the flexbox stretch fix?", "Use Scale With Container if you want 100%/auto fluid width. This page prioritizes not being stretched by the flex line."),
            ("Will path data change when I fix flexbox stretching?", "No. Only preserveAspectRatio and root CSS. Geometry stays."),
        ],
        "Paste an SVG that squashes in flex. Click Fix flexbox stretch.",
    ),
    page(
        "layout_box", "prevent-svg-distortion-in-css-grid",
        "Prevent SVG Distortion in CSS Grid — Free Tool | getsvgeditor.com",
        "Prevent SVG distortion in CSS grid. Lock meet and center the item so a grid cell cannot squash it — free tool.",
        "Prevent SVG Distortion in CSS Grid", "Prevent grid distortion",
        "Keep aspect in a <strong>grid cell</strong> with meet + justify-self/align-self center — not a gradient fix",
        "Prevent SVG distortion in CSS grid in SVGEditor",
        "Prevent SVG Distortion in CSS Grid",
        ["Prevent SVG distortion in CSS grid", "SVG grid cell squash fix", "CSS grid SVG aspect", "Stop SVG stretch in grid"],
        "Free online tool to prevent SVG distortion in CSS grid cells using meet and self-alignment.",
        ["xMidYMid meet", "justify-self center", "max-width 100%", "No upload"],
        "Prevent SVG distortion in CSS grid",
        "Set meet and grid self-alignment so the cell cannot squash the art.",
        "Click Prevent grid distortion. meet is set and root style uses max-width:100% plus center alignment.",
        "Prevent grid distortion", "Prevent this SVG distorting in CSS grid",
        [
            ("Why does CSS grid distort my SVG?", "A 1fr cell with both axes stretched can force the SVG box. This tool sets meet and centers the item so the cell no longer squash-scales the art."),
            ("How is grid distortion different from flexbox stretching?", "Grid uses tracks and justify-self/align-self. Flexbox uses flex-shrink. Use the matching page for the parent you actually have."),
            ("Does prevent-distortion change gradientUnits?", "No. For objectBoundingBox gradients in a grid, use Fix SVG Gradient Stretch in CSS Grid."),
            ("Can I still fill the cell without distortion?", "Yes — meet letterboxes. Slice would crop. This page chooses meet so nothing is clipped."),
        ],
        "Paste an SVG that squashes in grid. Click Prevent grid distortion.",
    ),
    page(
        "exporter_ns", "remove-inkscape-namespaces-from-svg",
        "Remove Inkscape Namespaces From SVG — Free Tool | getsvgeditor.com",
        "Remove Inkscape namespaces from SVG. Drop xmlns:inkscape and inkscape:* attributes — free, no upload.",
        "Remove Inkscape Namespaces From SVG", "Remove Inkscape NS",
        "Delete <code>xmlns:inkscape</code> and every <code>inkscape:*</code> attribute — sodipodi stays unless you use that tool",
        "Remove Inkscape namespaces from SVG in SVGEditor",
        "Remove Inkscape Namespaces From SVG",
        ["Remove Inkscape namespaces from SVG", "Strip xmlns:inkscape", "Delete inkscape: attributes", "Inkscape SVG namespace cleaner"],
        "Free online tool to remove Inkscape namespaces and inkscape:* attributes from SVG.",
        ["Drops xmlns:inkscape", "Removes inkscape:* attrs", "Keeps drawable shapes", "No upload"],
        "Remove Inkscape namespaces from SVG",
        "Strip Inkscape-only namespace declarations and attributes.",
        "Click Remove Inkscape NS. inkscape attributes and the Inkscape xmlns are deleted.",
        "Remove Inkscape NS", "Remove Inkscape namespaces from this SVG",
        [
            ("What does remove Inkscape namespaces from SVG delete?", "xmlns:inkscape and attributes/elements prefixed inkscape:. Visible paths and fills stay."),
            ("Will sodipodi attributes survive an Inkscape namespace pass?", "Yes. Inkscape and sodipodi ship together but this page only targets inkscape. Use Remove sodipodi attributes next."),
            ("Is this the same as Clean Illustrator SVG?", "No. Illustrator cleanup also hits Adobe i:* and metadata. This page is Inkscape-namespace-only."),
            ("Do I need Inkscape namespaces for the file to open in Inkscape again?", "No. Inkscape reopens standard SVG. The prefixes are editor leftovers."),
        ],
        "Paste an Inkscape export. Click Remove Inkscape NS.",
    ),
    page(
        "exporter_ns", "remove-sodipodi-attributes-from-svg",
        "Remove Sodipodi Attributes From SVG — Free Tool | getsvgeditor.com",
        "Remove sodipodi attributes from SVG. Strip xmlns:sodipodi and sodipodi:* leftovers — free browser tool.",
        "Remove Sodipodi Attributes From SVG", "Remove sodipodi attrs",
        "Delete <code>sodipodi:*</code> attributes and <code>xmlns:sodipodi</code> — Inkscape prefixes are a separate pass",
        "Remove sodipodi attributes from SVG in SVGEditor",
        "Remove Sodipodi Attributes From SVG",
        ["Remove sodipodi attributes from SVG", "Strip xmlns:sodipodi", "Delete sodipodi:namedview", "Sodipodi SVG cleaner"],
        "Free online tool to remove sodipodi attributes and the sodipodi namespace from SVG.",
        ["Drops xmlns:sodipodi", "Removes sodipodi:*", "Keeps vectors", "No upload"],
        "Remove sodipodi attributes from SVG",
        "Strip sodipodi editor attributes from the tree.",
        "Click Remove sodipodi attrs. sodipodi attributes, namedview leftovers, and the namespace are removed.",
        "Remove sodipodi attrs", "Remove sodipodi attributes from this SVG",
        [
            ("What are sodipodi attributes on an SVG?", "Leftovers from Inkscape’s older Sodipodi core — sodipodi:namedview, sodipodi:absref, and the xmlns:sodipodi declaration."),
            ("Does remove-sodipodi also delete inkscape:label?", "No. That prefix is Inkscape. Run Remove Inkscape Namespaces if those remain."),
            ("Will removing sodipodi change how the graphic looks?", "No. Those attributes are editor chrome, not paint."),
            ("Should I remove unused namespaces after sodipodi?", "Yes if other empty xmlns:* remain. Use Remove Unused SVG Namespaces."),
        ],
        "Paste SVG with sodipodi: attrs. Click Remove sodipodi attrs.",
    ),
    page(
        "exporter_ns", "clean-sketch-svg-export-online",
        "Clean Sketch SVG Export Online — Free Tool | getsvgeditor.com",
        "Clean Sketch SVG export online. Strip xmlns:sketch, sketch:type, and Sketch slice leftovers — free, no upload.",
        "Clean Sketch SVG Export Online", "Clean Sketch SVG",
        "Remove <strong>Sketch</strong> xmlns:sketch / sketch:type leftovers — not Figma data-name or Illustrator i:*",
        "Clean Sketch SVG export online in SVGEditor",
        "Clean Sketch SVG Export Online",
        ["Clean Sketch SVG export online", "Remove sketch:type from SVG", "Strip xmlns:sketch", "Sketch SVG cleaner"],
        "Free online tool to clean Sketch SVG exports: drop sketch namespace and slice metadata.",
        ["Drops xmlns:sketch", "Removes sketch:* attrs", "Keeps paths", "No upload"],
        "Clean Sketch SVG export online",
        "Strip Sketch exporter naming from SVG.",
        "Click Clean Sketch SVG. sketch:type, slice ids, and the Sketch xmlns are removed.",
        "Clean Sketch SVG", "Clean Sketch leftovers from this SVG",
        [
            ("What does clean Sketch SVG export online remove?", "xmlns:sketch, sketch:type, and Sketch slice/artboard attributes. Geometry stays."),
            ("Is Sketch cleanup the same as Clean Figma SVG?", "No. Figma uses data-name and Frame ids. Sketch uses the sketch: prefix."),
            ("Will layer names in Sketch survive this cleaner?", "Human titles in <title> stay. sketch:* attributes do not."),
            ("Can I also drop unused namespaces after a Sketch export?", "Yes. Remove Unused SVG Namespaces clears empty xmlns leftovers."),
        ],
        "Paste a Sketch SVG export. Click Clean Sketch SVG.",
    ),
    page(
        "exporter_ns", "remove-unused-svg-namespaces-online",
        "Remove Unused SVG Namespaces Online — Free Tool | getsvgeditor.com",
        "Remove unused SVG namespaces online. Drop xmlns:* prefixes that no element or attribute uses — free tool.",
        "Remove Unused SVG Namespaces Online", "Unused namespaces",
        "Keep <code>xmlns</code> for SVG itself; delete <strong>unused</strong> xmlns:foo declarations",
        "Remove unused SVG namespaces online in SVGEditor",
        "Remove Unused SVG Namespaces Online",
        ["Remove unused SVG namespaces online", "Strip unused xmlns from SVG", "Delete dead SVG namespaces", "SVG xmlns cleaner"],
        "Free online tool to remove unused xmlns:* namespace declarations from SVG markup.",
        ["Scans used prefixes", "Drops unused xmlns:*", "Keeps xlink if used", "No upload"],
        "Remove unused SVG namespaces online",
        "Delete namespace declarations that nothing references.",
        "Click Remove unused NS. Unused xmlns:* attributes on the root are deleted.",
        "Remove unused NS", "Remove unused SVG namespace declarations",
        [
            ("How does remove unused SVG namespaces decide what to drop?", "It scans element prefixes and attribute prefixes. A xmlns:foo with no foo:* usage is removed. The SVG xmlns stays."),
            ("Will xlink:href survive unused-namespace cleanup?", "If any xlink: attribute exists, xmlns:xlink is kept. Otherwise it is dropped."),
            ("Is this safer than removing Inkscape namespaces by name?", "This pass is prefix-usage based. The Inkscape/sodipodi/Sketch pages target those exporters even if you still want a surgical list."),
            ("Do unused namespaces change rendering?", "Browsers ignore unused xmlns. Removing them only shrinks markup."),
        ],
        "Paste SVG with extra xmlns:*. Click Remove unused NS.",
    ),
    page(
        "bbox", "crop-svg-to-bounding-box",
        "Crop SVG to Bounding Box — Free Tool | getsvgeditor.com",
        "Crop SVG to bounding box. Tight viewBox around painted content with no extra pad — free live preview.",
        "Crop SVG to Bounding Box", "Crop to bounding box",
        "Set viewBox to the <strong>tight content box</strong> (no 2% pad) — different from Crop SVG Online",
        "Crop SVG to bounding box in SVGEditor",
        "Crop SVG to Bounding Box",
        ["Crop SVG to bounding box", "Tight SVG viewBox crop", "SVG content bbox crop", "Trim SVG canvas to artwork"],
        "Free online tool to crop an SVG viewBox to the exact content bounding box.",
        ["Tight getBBox crop", "No pad ratio", "Root width/height removed", "No upload"],
        "Crop SVG to bounding box",
        "Fit viewBox to the measured content box.",
        "Click Crop to bounding box. viewBox becomes the tight content box; root width/height are removed.",
        "Crop to bounding box", "Crop this SVG to its bounding box",
        [
            ("How is crop SVG to bounding box different from Crop SVG Online?", "Crop SVG Online adds a small pad. This page uses a tight bounding box with no pad ratio so the canvas hugs the paint."),
            ("Does crop-to-bbox change path coordinates?", "No. Only viewBox (and root size attrs). Points stay in the same user space."),
            ("What if I only want the numbers, not a crop?", "Use Calculate SVG Bounding Box Online — it reports x/y/width/height without rewriting viewBox."),
            ("Will stroke width be included in the bounding box?", "Yes. Measurement includes stroke outset so outlines are not clipped."),
        ],
        "Paste a loose-canvas SVG. Click Crop to bounding box.",
    ),
    page(
        "bbox", "calculate-svg-bounding-box-online",
        "Calculate SVG Bounding Box Online — Free Tool | getsvgeditor.com",
        "Calculate SVG bounding box online. Measure content x, y, width, height without cropping viewBox — free tool.",
        "Calculate SVG Bounding Box Online", "Calculate bounding box",
        "Measure the content box and write it into <code>&lt;desc&gt;</code> — <strong>viewBox stays</strong>",
        "Calculate SVG bounding box online in SVGEditor",
        "Calculate SVG Bounding Box Online",
        ["Calculate SVG bounding box online", "Measure SVG getBBox", "SVG content box calculator", "Read SVG bounding box"],
        "Free online tool to calculate an SVG content bounding box without changing the viewBox.",
        ["Reports x y width height", "Keeps viewBox", "Optional overlay rect", "No upload"],
        "Calculate SVG bounding box online",
        "Measure painted content and store the box.",
        "Click Calculate bounding box. A <desc> records x/y/width/height and a dashed overlay shows the box.",
        "Calculate bounding box", "Calculate this SVG’s bounding box",
        [
            ("Does calculate SVG bounding box change the viewBox?", "No. It measures content, writes the numbers into <desc>, and draws a dashed overlay. Use Crop to Bounding Box to apply the box."),
            ("How is this different from Calculate SVG viewBox?", "Calculate viewBox derives or shows the root viewBox string. This page measures painted content, which can be smaller than the canvas."),
            ("Can I copy the bounding box numbers?", "Yes. They appear in the status line and inside <desc> in Source."),
            ("Are hidden or defs shapes included?", "No. Measurement skips defs, clipPath, mask, and invisible scaffolding."),
        ],
        "Paste an SVG. Click Calculate bounding box to read x/y/width/height.",
    ),
    page(
        "paint_inherit", "convert-svg-colors-to-currentcolor",
        "Convert SVG Colors to currentColor — Free Tool | getsvgeditor.com",
        "Convert SVG colors to currentColor. Rewrite fill and stroke paints so the icon inherits CSS color — free tool.",
        "Convert SVG Colors to currentColor", "Colors → currentColor",
        "Set both <strong>fill and stroke</strong> to currentColor — not fill-only",
        "Convert SVG colors to currentColor in SVGEditor",
        "Convert SVG Colors to currentColor",
        ["Convert SVG colors to currentColor", "SVG fill and stroke currentColor", "Inherit CSS color on SVG", "Themable SVG paints"],
        "Free online tool to convert SVG fill and stroke colors to currentColor for CSS theming.",
        ["Fills → currentColor", "Strokes → currentColor", "url() paints kept", "No upload"],
        "Convert SVG colors to currentColor",
        "Replace hardcoded fill and stroke with currentColor.",
        "Click Convert to currentColor. Solid fill and stroke paints become currentColor; gradients stay.",
        "Convert to currentColor", "Convert fill and stroke to currentColor",
        [
            ("How is convert SVG colors to currentColor different from fill-only?", "Convert SVG Fill to currentColor leaves strokes. This page rewrites both fill and stroke so the whole icon follows CSS color."),
            ("Do gradient fills become currentColor?", "No. url(#) paints stay so gradient defs keep working."),
            ("Will none fills be turned into currentColor?", "No. fill=\"none\" and stroke=\"none\" stay none."),
            ("How do I hover fill and stroke after currentColor?", "Use Change SVG Fill and Stroke on Hover for :hover rules. currentColor only sets inheritance."),
        ],
        "Paste a multi-color icon. Click Convert to currentColor.",
    ),
    page(
        "paint_inherit", "remove-hardcoded-stroke-from-svg",
        "Remove Hardcoded Stroke From SVG — Free Tool | getsvgeditor.com",
        "Remove hardcoded stroke from SVG. Drop stroke, stroke-width, and stroke-* so CSS can own the outline — free.",
        "Remove Hardcoded Stroke From SVG", "Remove hardcoded stroke",
        "Delete hardcoded <code>stroke</code> paints — fills stay; this is not a fill remover",
        "Remove hardcoded stroke from SVG in SVGEditor",
        "Remove Hardcoded Stroke From SVG",
        ["Remove hardcoded stroke from SVG", "Strip SVG stroke attributes", "Delete stroke-width from SVG", "SVG without hardcoded outline"],
        "Free online tool to remove hardcoded stroke attributes from SVG so CSS can style outlines.",
        ["Removes stroke paints", "Drops stroke-width / dash", "Keeps fills", "No upload"],
        "Remove hardcoded stroke from SVG",
        "Strip stroke presentation from elements.",
        "Click Remove hardcoded stroke. stroke, stroke-width, and related attributes are removed; fills remain.",
        "Remove hardcoded stroke", "Remove hardcoded stroke attributes",
        [
            ("What does remove hardcoded stroke from SVG delete?", "stroke, stroke-width, stroke-linecap, stroke-linejoin, stroke-dasharray, and stroke in style=\"…\". Fill attributes stay."),
            ("Is this the same as Remove hardcoded fill from SVG paths?", "No. That page targets fill. This page only removes stroke so you can restyle outlines in CSS."),
            ("Will a stroke-only icon disappear?", "If there is no fill, removing stroke can hide the shape. Add a CSS stroke or convert paints to currentColor first."),
            ("Does this convert stroke to a filled path?", "No. Use Convert SVG Stroke to Path if you need an outline baked into geometry."),
        ],
        "Paste an outlined icon. Click Remove hardcoded stroke.",
    ),
    page(
        "paint_inherit", "change-svg-fill-and-stroke-on-hover",
        "Change SVG Fill and Stroke on Hover — Free Tool | getsvgeditor.com",
        "Change SVG fill and stroke on hover. Add a CSS :hover rule for both paints — free live preview, no upload.",
        "Change SVG Fill and Stroke on Hover", "Fill + stroke hover",
        "Apply <code>:hover</code> to <strong>fill and stroke together</strong> — not fill-only hover",
        "Change SVG fill and stroke on hover in SVGEditor",
        "Change SVG Fill and Stroke on Hover",
        ["Change SVG fill and stroke on hover", "SVG hover fill and outline", "CSS hover stroke SVG", "Interactive SVG paints"],
        "Free online tool to change SVG fill and stroke on hover with a CSS :hover rule.",
        [":hover fill + stroke", "Removes hardcoded paints", "Live preview hover", "No upload"],
        "Change SVG fill and stroke on hover",
        "Add a class and :hover rule for both paints.",
        "Click Apply fill+stroke hover. Shapes get a class; hover the preview to see both paints change.",
        "Apply fill+stroke hover", "Change fill and stroke on hover",
        [
            ("How do I change SVG fill and stroke on hover?", "Click Apply fill+stroke hover. A <style> rule sets resting and :hover fill and stroke. Hover the preview to verify."),
            ("How is this different from Change SVG Fill Color on Hover?", "Fill-on-hover only restyles fill. This page updates fill and stroke in the same :hover rule."),
            ("Why doesn’t hover work if I leave hardcoded stroke attributes?", "Presentation attributes can override CSS. This pass removes them so the class rule wins."),
            ("Can I use currentColor and hover together?", "Convert colors to currentColor for inheritance, then add hover if you need a second explicit color."),
        ],
        "Paste a filled+stroked icon. Click Apply fill+stroke hover, then hover the preview.",
    ),
]


def main():
    assert len(PAGES) == 42, f"expected 42 pages, got {len(PAGES)}"
    questions = [q for p in PAGES for q, _ in p["faqs"]]
    dups = sorted({q for q in questions if questions.count(q) > 1})
    assert len(questions) == len(set(questions)), f"duplicate FAQ questions: {dups}"
    for p in PAGES:
        assert len(p["faqs"]) == 4, p["slug"]
        assert 2 <= len(p["guides"]) <= 4, (p["slug"], len(p["guides"]))
        build_page(p)
    slugs_path = Path(__file__).resolve().parent / "_craft_slugs.txt"
    slugs_path.write_text("\n".join(p["slug"] for p in PAGES) + "\n", encoding="utf-8")
    print("wrote", slugs_path)
    print("done", len(PAGES))


if __name__ == "__main__":
    main()
