#!/usr/bin/env python3
"""Generate SVG→PNG long-tail intent pages."""
from pathlib import Path

from tool_page_builder import build_page, note, guides

ROOT = Path(__file__).resolve().parent.parent

CLUSTERS = {
    "png_alpha": [
        "/convert-svg-to-transparent-png",
        "/export-svg-as-transparent-png",
        "/svg-to-png-without-background",
        "/svg-to-png-high-resolution",
    ],
    "png_res": [
        "/svg-to-png-high-resolution",
        "/svg-to-retina-png-online",
        "/svg-to-png-2x-scale",
        "/svg-to-png-512-pixels",
        "/svg-to-png-custom-size",
    ],
    "png_asset": [
        "/svg-icon-to-png-converter",
        "/svg-logo-to-png-online",
        "/svg-favicon-to-png-converter",
        "/svg-illustration-to-png-online",
        "/svg-to-apple-touch-icon",
    ],
    "png_input": [
        "/svg-code-to-png-online",
        "/inline-svg-to-png-converter",
        "/paste-svg-export-as-png",
        "/download-svg-as-png-online",
        "/convert-svg-path-to-png",
        "/batch-convert-svg-to-png",
    ],
    "png_use": [
        "/svg-to-png-custom-size",
        "/svg-to-png-for-email",
        "/batch-convert-svg-to-png",
        "/svg-to-png-512-pixels",
    ],
}

LABEL = {
    "/convert-svg-to-transparent-png": "Transparent PNG",
    "/export-svg-as-transparent-png": "Export transparent PNG",
    "/svg-to-png-without-background": "PNG without background",
    "/svg-to-png-high-resolution": "High-resolution PNG",
    "/svg-to-retina-png-online": "Retina PNG",
    "/svg-to-png-2x-scale": "2× PNG",
    "/svg-to-png-512-pixels": "512px PNG",
    "/svg-to-png-custom-size": "Custom-size PNG",
    "/svg-icon-to-png-converter": "Icon → PNG",
    "/svg-logo-to-png-online": "Logo → PNG",
    "/svg-favicon-to-png-converter": "Favicon PNG",
    "/svg-illustration-to-png-online": "Illustration → PNG",
    "/svg-to-apple-touch-icon": "Apple touch icon",
    "/svg-code-to-png-online": "SVG code → PNG",
    "/inline-svg-to-png-converter": "Inline SVG → PNG",
    "/paste-svg-export-as-png": "Paste → PNG",
    "/download-svg-as-png-online": "Download as PNG",
    "/convert-svg-path-to-png": "Path → PNG",
    "/svg-to-png-for-email": "PNG for email",
    "/batch-convert-svg-to-png": "Batch SVG → PNG",
}


def cluster_guides(cluster, slug):
    hrefs = [h for h in CLUSTERS[cluster] if h != f"/{slug}"]
    return guides([(h, LABEL.get(h, h.strip("/"))) for h in hrefs[:4]])


def cluster_note(cluster, slug):
    hrefs = [h for h in CLUSTERS[cluster] if h != f"/{slug}"]
    a, b = hrefs[0], hrefs[1]
    return note(a, LABEL.get(a, a), b, LABEL.get(b, b))


def page(cluster, slug, title, description, h1, crumb, sub, og_alt, app_name, app_alts, app_desc, features, howto_name, howto_desc, howto_click, btn, btn_title, faqs, empty, extra_inputs=None):
    p = {
        "family": "png",
        "cluster": cluster,
        "slug": slug,
        "title": title,
        "description": description,
        "h1": h1,
        "crumb": crumb,
        "sub": sub,
        "og_alt": og_alt,
        "app_name": app_name,
        "app_alts": app_alts,
        "app_desc": app_desc,
        "features": features,
        "howto_name": howto_name,
        "howto_desc": howto_desc,
        "howto_click": howto_click,
        "btn": btn,
        "btn_title": btn_title,
        "faq_aria": f"{h1} FAQ",
        "faqs": faqs,
        "note_html": cluster_note(cluster, slug),
        "guides": cluster_guides(cluster, slug),
        "empty": empty,
    }
    if extra_inputs:
        p["extra_inputs"] = extra_inputs
    return p


PAGES = [
    page(
        "png_alpha", "convert-svg-to-transparent-png",
        "Convert SVG to Transparent PNG — Free Tool | getsvgeditor.com",
        "Convert SVG to transparent PNG. Strip a solid backdrop and download an alpha PNG — free, in your browser.",
        "Convert SVG to Transparent PNG", "Transparent PNG",
        "Rasterize to PNG with a <strong>transparent backdrop</strong> — solid canvas fills are stripped first",
        "Convert SVG to transparent PNG in SVGEditor",
        "Convert SVG to Transparent PNG",
        ["Convert SVG to transparent PNG", "SVG to PNG with alpha", "Transparent SVG raster", "SVG alpha PNG download"],
        "Free online tool to convert SVG to a transparent PNG by removing a solid backdrop before rasterizing.",
        ["Strips solid backdrop", "Keeps alpha", "2× default raster", "No upload required"],
        "Convert SVG to transparent PNG",
        "Remove a full-canvas fill, then download a transparent PNG.",
        "Click Convert to transparent PNG. A full-size backdrop is removed, then a PNG with alpha downloads.",
        "Convert to transparent PNG", "Convert this SVG to a transparent PNG",
        [
            ("How do I convert SVG to a transparent PNG?", "Paste the SVG and click Convert to transparent PNG. A full-canvas backdrop is stripped, then the PNG tab rasterizes with a clear background."),
            ("Is convert-to-transparent-png the same as export SVG as transparent PNG?", "Same alpha idea, different button: convert also strips a detected backdrop. Export transparent PNG downloads alpha as-is without that cleanup."),
            ("Will icon fills become see-through?", "No. Only a canvas-sized backdrop (or data-svgeditor-bg) is removed. Shape fills stay."),
            ("Does the PNG stay transparent in slides and Figma?", "Yes. The file has an alpha channel. Place it on any background."),
        ],
        "Paste an SVG with a solid canvas. Click Convert to transparent PNG.",
    ),
    page(
        "png_res", "svg-to-png-high-resolution",
        "SVG to PNG High Resolution — Free Tool | getsvgeditor.com",
        "SVG to PNG high resolution. Rasterize at 4× so the PNG stays sharp in print and zoom — free browser export.",
        "SVG to PNG High Resolution", "High-resolution PNG",
        "Export a <strong>4×</strong> PNG from the vector — sharper than the default 2× preview scale",
        "SVG to PNG high resolution in SVGEditor",
        "SVG to PNG High Resolution",
        ["SVG to PNG high resolution", "4x SVG raster", "High DPI SVG to PNG", "Print-sharp SVG PNG"],
        "Free online tool to convert SVG to a high-resolution 4× PNG in the browser.",
        ["4× pixel scale", "Transparent canvas", "Root size attrs stripped", "No upload"],
        "SVG to PNG high resolution",
        "Rasterize the SVG at four times the viewBox size.",
        "Click Export high-res PNG. The PNG is drawn at 4× the viewBox, then downloads.",
        "Export high-res PNG", "Export this SVG as a high-resolution PNG",
        [
            ("What does SVG to PNG high resolution actually scale?", "The PNG pixel size is 4× the viewBox (or content aspect). Vectors stay crisp; you are not photographing a screenshot."),
            ("How is high-res different from retina PNG or 2× scale?", "High-res is 4×. Retina PNG uses 3×. 2× scale is the @2x asset size."),
            ("Will a huge 4× PNG freeze the tab?", "Very large viewBoxes can. If the canvas is already 2000px, try Custom Size instead of 4×."),
            ("Is the high-res PNG transparent?", "Yes. The canvas is cleared before drawImage — no white plate unless your SVG paints one."),
        ],
        "Paste an SVG. Click Export high-res PNG for a 4× raster.",
    ),
    page(
        "png_asset", "svg-icon-to-png-converter",
        "SVG Icon to PNG Converter — Free Tool | getsvgeditor.com",
        "SVG icon to PNG converter. Export a 256px app/icon raster with a transparent canvas — free, no upload.",
        "SVG Icon to PNG Converter", "Icon → PNG",
        "Rasterize an <strong>icon</strong> to a 256px PNG — not a logo lockup or favicon 32px",
        "SVG icon to PNG converter in SVGEditor",
        "SVG Icon to PNG Converter",
        ["SVG icon to PNG converter", "256px SVG icon PNG", "App icon from SVG", "Icon raster export"],
        "Free online converter from SVG icon markup to a 256px transparent PNG.",
        ["256px wide", "Keeps aspect", "Alpha canvas", "No upload"],
        "SVG icon to PNG converter",
        "Export the icon at 256px on the long edge.",
        "Click Convert icon to PNG. A 256px PNG downloads from the live SVG.",
        "Convert icon to PNG", "Convert this SVG icon to PNG",
        [
            ("What size is the SVG icon to PNG converter?", "256px on the width, height follows viewBox aspect. Use 512 Pixels or Apple Touch Icon for those exact sizes."),
            ("Should I use this for a wordmark logo?", "Use SVG Logo to PNG Online — that export is 800px wide for lockups."),
            ("Does the icon PNG include a background tile?", "No. The raster is transparent around the glyph."),
            ("Can I start from the sample bookmark icon?", "Yes. The page loads a bookmark glyph with viewBox only. Click the button to download PNG."),
        ],
        "Paste an SVG icon. Click Convert icon to PNG.",
    ),
    page(
        "png_asset", "svg-logo-to-png-online",
        "SVG Logo to PNG Online — Free Tool | getsvgeditor.com",
        "SVG logo to PNG online. Export an 800px-wide lockup PNG for decks and press kits — free in the browser.",
        "SVG Logo to PNG Online", "Logo → PNG",
        "Export a <strong>logo lockup</strong> at 800px wide — larger than the 256px icon converter",
        "SVG logo to PNG online in SVGEditor",
        "SVG Logo to PNG Online",
        ["SVG logo to PNG online", "800px logo PNG", "Brand lockup raster", "SVG wordmark to PNG"],
        "Free online tool to convert an SVG logo to an 800px-wide PNG.",
        ["800px width", "Aspect preserved", "Transparent plate", "No upload"],
        "SVG logo to PNG online",
        "Rasterize the lockup at 800px wide.",
        "Click Export logo PNG. An 800px-wide PNG downloads.",
        "Export logo PNG", "Export this SVG logo as PNG",
        [
            ("Why 800px for SVG logo to PNG online?", "Logos in slides and sites usually need more width than a 256px icon. 800px is a practical lockup size; use Custom Size for a exact pixel box."),
            ("Will the wordmark stay sharp at 800px?", "Yes. It is rasterized from vectors, not upscaled from a small bitmap."),
            ("Is logo PNG the same as illustration PNG?", "No. Illustration export targets 1024px for scenes. Logo is 800px for a mark."),
            ("Can I keep a transparent plate behind the logo?", "Yes. No backdrop is painted unless your SVG includes one."),
        ],
        "Paste an SVG logo. Click Export logo PNG.",
    ),
    page(
        "png_use", "svg-to-png-custom-size",
        "SVG to PNG Custom Size — Free Tool | getsvgeditor.com",
        "SVG to PNG custom size. Set width and height in pixels, then download that exact PNG — free browser tool.",
        "SVG to PNG Custom Size", "Custom-size PNG",
        "Type a <strong>pixel width and height</strong> and export that exact PNG canvas",
        "SVG to PNG custom size in SVGEditor",
        "SVG to PNG Custom Size",
        ["SVG to PNG custom size", "SVG PNG exact pixels", "Resize SVG export PNG", "Custom canvas SVG raster"],
        "Free online tool to export SVG as a PNG at a custom width and height.",
        ["Width + height inputs", "Exact pixel canvas", "Transparent unused area", "No upload"],
        "SVG to PNG custom size",
        "Rasterize into the width×height you type.",
        "Set width and height, then click Export custom PNG. The PNG canvas matches those pixels.",
        "Export custom PNG", "Export PNG at a custom size",
        [
            ("How do I export SVG to PNG at a custom size?", "Enter width and height in the toolbar and click Export custom PNG. The canvas is exactly those pixels."),
            ("What if my SVG aspect does not match the box?", "The graphic is drawn with meet into the canvas. Extra area stays transparent — it does not stretch."),
            ("How is custom size different from 512 pixels?", "512 Pixels forces a 512×512 square. Custom Size is any pair you type (default 640×360)."),
            ("Do I need root width/height on the SVG?", "No. Those attributes are stripped. Pixel size comes from the inputs."),
        ],
        "Paste an SVG, set pixels, click Export custom PNG.",
        extra_inputs=[
            {"id": "png-width-input", "label": "W", "default": "640", "aria": "PNG width in pixels"},
            {"id": "png-height-input", "label": "H", "default": "360", "aria": "PNG height in pixels"},
        ],
    ),
    page(
        "png_res", "svg-to-retina-png-online",
        "SVG to Retina PNG Online — Free Tool | getsvgeditor.com",
        "SVG to retina PNG online. Export a 3× (@3x) PNG for high-DPI screens — free, no upload.",
        "SVG to Retina PNG Online", "Retina PNG",
        "Download an <strong>@3x</strong> retina PNG — not 2× and not the 4× high-res pass",
        "SVG to retina PNG online in SVGEditor",
        "SVG to Retina PNG Online",
        ["SVG to retina PNG online", "SVG @3x PNG", "Retina raster from SVG", "High-DPI SVG export"],
        "Free online tool to convert SVG to a retina @3x PNG.",
        ["3× scale", "Transparent canvas", "Named @3x file", "No upload"],
        "SVG to retina PNG online",
        "Rasterize at triple resolution for retina displays.",
        "Click Export retina PNG. The download is 3× the viewBox, filename ends with @3x.",
        "Export retina PNG", "Export this SVG as a retina PNG",
        [
            ("What scale is SVG to retina PNG online?", "3× the viewBox — the common @3x asset. Use 2× Scale for @2x and High Resolution for 4×."),
            ("Why not always export 4× for retina?", "4× files are heavier than phones need. @3x matches modern iPhone asset catalogs."),
            ("Is the retina PNG transparent?", "Yes. The canvas is cleared first."),
            ("Does retina export change the SVG source?", "It only strips root width/height. Geometry is unchanged."),
        ],
        "Paste an SVG. Click Export retina PNG for a 3× file.",
    ),
    page(
        "png_input", "svg-code-to-png-online",
        "SVG Code to PNG Online — Free Tool | getsvgeditor.com",
        "SVG code to PNG online. Paste raw <svg> markup and download a PNG — free live preview.",
        "SVG Code to PNG Online", "SVG code → PNG",
        "Turn <strong>source markup</strong> in the editor into a PNG — you paste code, not a binary",
        "SVG code to PNG online in SVGEditor",
        "SVG Code to PNG Online",
        ["SVG code to PNG online", "Paste SVG markup PNG", "SVG source to raster", "Code editor SVG export"],
        "Free online tool to convert pasted SVG code into a PNG download.",
        ["Reads Source panel", "2× raster", "Live preview", "No upload"],
        "SVG code to PNG online",
        "Rasterize whatever markup is in Source.",
        "Click PNG from SVG code. The current Source markup is rasterized and downloaded.",
        "PNG from SVG code", "Convert this SVG code to PNG",
        [
            ("Do I upload a .svg file for SVG code to PNG?", "You can, but the intent is paste: drop <svg>…</svg> into Source and click the button."),
            ("What if my snippet is wrapped in HTML?", "The extractor pulls the first <svg>…</svg> block from the paste."),
            ("How is this different from inline SVG to PNG?", "Inline is for markup already sitting in an HTML page. Code-to-PNG is the raw editor document."),
            ("Does invalid SVG code still export?", "No. You will get an error until the markup parses."),
        ],
        "Paste SVG code into Source. Click PNG from SVG code.",
    ),
    page(
        "png_input", "inline-svg-to-png-converter",
        "Inline SVG to PNG Converter — Free Tool | getsvgeditor.com",
        "Inline SVG to PNG converter. Copy an in-page <svg> and export PNG without a separate file — free tool.",
        "Inline SVG to PNG Converter", "Inline SVG → PNG",
        "Convert an <strong>inline &lt;svg&gt;</strong> copied from HTML into a PNG",
        "Inline SVG to PNG converter in SVGEditor",
        "Inline SVG to PNG Converter",
        ["Inline SVG to PNG converter", "HTML inline SVG raster", "In-page SVG to PNG", "Copy inline SVG export"],
        "Free online converter for inline HTML SVG markup to PNG.",
        ["Accepts inline paste", "Strips XML prolog if present", "2× PNG", "No upload"],
        "Inline SVG to PNG converter",
        "Export a PNG from inline HTML SVG markup.",
        "Click Convert inline SVG. The inline markup is cleaned and a PNG downloads.",
        "Convert inline SVG", "Convert this inline SVG to PNG",
        [
            ("Can I paste an inline SVG that still has HTML around it?", "Yes. The first <svg>…</svg> is extracted from the clipboard dump."),
            ("Why a separate page from SVG code to PNG?", "Inline pages usually include class/role from HTML. This pass is framed for that paste; code-to-PNG is the raw source workflow."),
            ("Will width/height on the inline root affect the PNG?", "They are stripped. Size comes from viewBox and the 2× scale."),
            ("Does inline export keep CSS classes?", "Classes stay in the SVG. External page CSS does not travel with the paste."),
        ],
        "Paste an inline <svg> from HTML. Click Convert inline SVG.",
    ),
    page(
        "png_alpha", "export-svg-as-transparent-png",
        "Export SVG as Transparent PNG — Free Tool | getsvgeditor.com",
        "Export SVG as transparent PNG. Download alpha PNG as painted — no backdrop strip — free browser export.",
        "Export SVG as Transparent PNG", "Export transparent PNG",
        "Download PNG with a <strong>clear canvas</strong> without deleting shapes — as-painted alpha",
        "Export SVG as transparent PNG in SVGEditor",
        "Export SVG as Transparent PNG",
        ["Export SVG as transparent PNG", "Download SVG alpha PNG", "Save SVG with transparency", "Transparent PNG export"],
        "Free online tool to export SVG as a transparent PNG without rewriting fills.",
        ["Clear canvas", "No backdrop strip", "2× raster", "No upload"],
        "Export SVG as transparent PNG",
        "Rasterize on a cleared canvas and download.",
        "Click Export transparent PNG. The PNG has alpha; artwork fills are not removed.",
        "Export transparent PNG", "Export this SVG as a transparent PNG",
        [
            ("How is export SVG as transparent PNG different from convert to transparent PNG?", "Export does not delete a backdrop rectangle. Convert strips a full-canvas fill first. Use Without Background if you know there is a plate to remove."),
            ("Why is my export still white?", "The SVG itself paints a white rect. Use Convert to Transparent PNG or Without Background."),
            ("What scale is the export?", "2× the viewBox. Switch to High Resolution or Retina for 4× / 3×."),
            ("Does export rewrite my SVG source?", "Only root width/height are removed so the vector stays fluid."),
        ],
        "Paste an SVG. Click Export transparent PNG.",
    ),
    page(
        "png_alpha", "svg-to-png-without-background",
        "SVG to PNG Without Background — Free Tool | getsvgeditor.com",
        "SVG to PNG without background. Remove a white or solid plate, then download alpha PNG — free tool.",
        "SVG to PNG Without Background", "PNG without background",
        "Delete a <strong>background plate</strong> (white/solid canvas) then rasterize — aimed at leftover artboards",
        "SVG to PNG without background in SVGEditor",
        "SVG to PNG Without Background",
        ["SVG to PNG without background", "Remove SVG plate then PNG", "PNG no background from SVG", "Knock out SVG backdrop"],
        "Free online tool to export SVG to PNG after removing a background plate.",
        ["Removes artboard plate", "Then alpha PNG", "Keeps glyph fills", "No upload"],
        "SVG to PNG without background",
        "Strip the plate, then download PNG.",
        "Click PNG without background. A backdrop rect is removed, then the PNG downloads.",
        "PNG without background", "Export PNG without a background plate",
        [
            ("What counts as a background on SVG to PNG without background?", "A full-viewBox rect, data-svgeditor-bg, or a near-white canvas fill. Icon colors are not treated as a plate."),
            ("How is this different from convert to transparent PNG?", "Same family: both strip a plate. This page’s sample is a cream artboard; convert’s sample is a white hex tile. Copy and FAQs stay distinct."),
            ("Will a photo-like illustration lose its sky?", "Only a canvas-sized rect is removed. Illustrated skies that are not a full-bleed rect stay."),
            ("Can I preview after the plate is gone?", "Yes. Source updates, then the PNG tab shows alpha."),
        ],
        "Paste an SVG with an artboard fill. Click PNG without background.",
    ),
    page(
        "png_asset", "svg-favicon-to-png-converter",
        "SVG Favicon to PNG Converter — Free Tool | getsvgeditor.com",
        "SVG favicon to PNG converter. Export a 32×32 PNG for classic favicon.ico workflows — free browser tool.",
        "SVG Favicon to PNG Converter", "Favicon PNG",
        "Rasterize to a <strong>32×32</strong> favicon PNG — not 180 Apple touch or 256 icon",
        "SVG favicon to PNG converter in SVGEditor",
        "SVG Favicon to PNG Converter",
        ["SVG favicon to PNG converter", "32x32 favicon from SVG", "SVG tab icon PNG", "Favicon raster export"],
        "Free online converter from SVG favicon markup to a 32×32 PNG.",
        ["32×32 canvas", "Meet into the square", "Transparent corners", "No upload"],
        "SVG favicon to PNG converter",
        "Draw the mark into a 32×32 PNG.",
        "Click Convert favicon PNG. A 32×32 PNG downloads.",
        "Convert favicon PNG", "Convert this SVG favicon to PNG",
        [
            ("What size is the SVG favicon to PNG converter?", "32×32 pixels. Use Apple Touch Icon for 180×180 and Icon Converter for 256."),
            ("Should a favicon PNG be square?", "Yes. Non-square viewBoxes are fitted with meet; extra pixels stay transparent."),
            ("Can I still ship an SVG favicon in browsers?", "Modern browsers accept SVG favicons. This PNG is for older tabs, apple-touch fallbacks, and ICO packing."),
            ("Is 16×16 available?", "Set Custom Size to 16×16 if you need the older tray size."),
        ],
        "Paste a favicon SVG. Click Convert favicon PNG.",
    ),
    page(
        "png_asset", "svg-illustration-to-png-online",
        "SVG Illustration to PNG Online — Free Tool | getsvgeditor.com",
        "SVG illustration to PNG online. Export a 1024px-wide scene PNG for posts and mockups — free tool.",
        "SVG Illustration to PNG Online", "Illustration → PNG",
        "Rasterize a <strong>scene</strong> at 1024px wide — larger than logo (800) or icon (256)",
        "SVG illustration to PNG online in SVGEditor",
        "SVG Illustration to PNG Online",
        ["SVG illustration to PNG online", "1024px illustration PNG", "Scene SVG raster", "Hero illustration export"],
        "Free online tool to convert an SVG illustration to a 1024px-wide PNG.",
        ["1024px width", "Scene-sized raster", "Alpha canvas", "No upload"],
        "SVG illustration to PNG online",
        "Export the illustration at 1024px wide.",
        "Click Export illustration PNG. A 1024px-wide PNG downloads.",
        "Export illustration PNG", "Export this SVG illustration as PNG",
        [
            ("Why 1024px for SVG illustration to PNG?", "Scenes need more pixels than icons. 1024 is a typical blog/hero still. Use High Resolution if you need 4× the viewBox instead."),
            ("Will tiny details survive 1024px?", "Yes if they exist in the vector. You are not photographing a small preview."),
            ("Is illustration PNG good for email?", "Email clients prefer ~600px wide. Use SVG to PNG for Email for that width."),
            ("Does export flatten gradients?", "They flatten into pixels in the PNG. Keep the SVG if you still need vectors."),
        ],
        "Paste an illustration SVG. Click Export illustration PNG.",
    ),
    page(
        "png_input", "download-svg-as-png-online",
        "Download SVG as PNG Online — Free Tool | getsvgeditor.com",
        "Download SVG as PNG online. One click saves the current graphic as a 2× PNG file — free, no account.",
        "Download SVG as PNG Online", "Download as PNG",
        "The <strong>download</strong> action: save the live SVG as a PNG file on disk",
        "Download SVG as PNG online in SVGEditor",
        "Download SVG as PNG Online",
        ["Download SVG as PNG online", "Save SVG to PNG file", "SVG PNG download button", "Get PNG from SVG"],
        "Free online tool to download the current SVG as a PNG file.",
        ["One-click download", "2× PNG", "Transparent canvas", "No account"],
        "Download SVG as PNG online",
        "Save the live preview as a PNG file.",
        "Click Download PNG. svgeditor-download.png is saved from the rasterized SVG.",
        "Download PNG", "Download this SVG as a PNG file",
        [
            ("Where does download SVG as PNG online save the file?", "Your browser’s Downloads folder, named svgeditor-download.png."),
            ("How is this different from paste SVG export as PNG?", "Download emphasizes saving the file already in the editor. Paste is the clipboard-to-export flow."),
            ("Can I download without changing Source?", "Yes. The SVG is only stripped of root width/height."),
            ("Is the downloaded PNG 1× or 2×?", "2× the viewBox so it stays sharp on typical screens."),
        ],
        "Paste an SVG. Click Download PNG.",
    ),
    page(
        "png_input", "paste-svg-export-as-png",
        "Paste SVG Export as PNG — Free Tool | getsvgeditor.com",
        "Paste SVG export as PNG. Drop markup from the clipboard and export a PNG immediately — free tool.",
        "Paste SVG Export as PNG", "Paste → PNG",
        "Clipboard-first: <strong>paste</strong> markup, then export PNG — sample is already in Source",
        "Paste SVG export as PNG in SVGEditor",
        "Paste SVG Export as PNG",
        ["Paste SVG export as PNG", "Clipboard SVG to PNG", "Paste markup raster", "Quick paste PNG export"],
        "Free online tool to paste SVG markup and export it as a PNG.",
        ["Clipboard paste", "2× PNG download", "Live preview", "No upload"],
        "Paste SVG export as PNG",
        "Export whatever you just pasted.",
        "Click Export pasted PNG. The Source paste is rasterized and downloaded.",
        "Export pasted PNG", "Export the pasted SVG as PNG",
        [
            ("Do I need to upload a file to paste SVG export as PNG?", "No. Paste into Source (Ctrl/Cmd+V) and click Export pasted PNG."),
            ("What if I paste several SVGs?", "This page exports the first <svg> block. Use Batch Convert SVG to PNG for multiple roots."),
            ("Does paste sanitize scripts?", "Yes. Unsafe script/event handlers are stripped before preview and raster."),
            ("Can I edit after paste before export?", "Yes. Tweak Source, then click the button."),
        ],
        "Paste SVG markup. Click Export pasted PNG.",
    ),
    page(
        "png_res", "svg-to-png-512-pixels",
        "SVG to PNG 512 Pixels — Free Tool | getsvgeditor.com",
        "SVG to PNG 512 pixels. Export a 512×512 square PNG for app stores and Discord — free browser tool.",
        "SVG to PNG 512 Pixels", "512px PNG",
        "Force a <strong>512×512</strong> square PNG — not 256 icon and not a free-aspect 2×",
        "SVG to PNG 512 pixels in SVGEditor",
        "SVG to PNG 512 Pixels",
        ["SVG to PNG 512 pixels", "512x512 SVG PNG", "App store SVG raster", "Square 512 PNG from SVG"],
        "Free online tool to convert SVG to a 512×512 PNG.",
        ["512×512 canvas", "Meet, no stretch", "Transparent padding", "No upload"],
        "SVG to PNG 512 pixels",
        "Fit the graphic into a 512×512 PNG.",
        "Click Export 512 PNG. A 512×512 PNG downloads with the art centered.",
        "Export 512 PNG", "Export this SVG as a 512×512 PNG",
        [
            ("Is SVG to PNG 512 pixels always a square?", "Yes. 512×512. Non-square art is centered with meet; padding is transparent."),
            ("How is 512 different from the icon converter?", "Icon export is 256px wide and keeps aspect. 512 is a square app-store tile."),
            ("Can I get 1024×1024?", "Use Custom Size and type 1024 and 1024."),
            ("Will the SVG be stretched to fill 512?", "No. meet preserves aspect."),
        ],
        "Paste an SVG. Click Export 512 PNG.",
    ),
    page(
        "png_input", "convert-svg-path-to-png",
        "Convert SVG Path to PNG — Free Tool | getsvgeditor.com",
        "Convert SVG path to PNG. Rasterize a <path> (or wrap d= in a canvas) to a sharp PNG — free tool.",
        "Convert SVG Path to PNG", "Path → PNG",
        "Export a <strong>&lt;path&gt;</strong> as PNG — sample is a single stroked curve, not a full logo",
        "Convert SVG path to PNG in SVGEditor",
        "Convert SVG Path to PNG",
        ["Convert SVG path to PNG", "SVG path data raster", "d attribute to PNG", "Path-only SVG export"],
        "Free online tool to convert an SVG path to a PNG image.",
        ["Path-focused sample", "3× sharp stroke", "Transparent canvas", "No upload"],
        "Convert SVG path to PNG",
        "Rasterize the path at 3× for a clean stroke.",
        "Click Convert path to PNG. The path is rasterized at 3× and downloaded.",
        "Convert path to PNG", "Convert this SVG path to PNG",
        [
            ("Can I paste only a d= string without <svg>?", "Wrap it in a simple <svg viewBox> with a <path>. The sample shows the expected shape."),
            ("Why 3× for path to PNG?", "Thin strokes alias at 1×. 3× keeps the curve clean without a 4× high-res file."),
            ("Does this convert the path to a filled outline?", "No. It rasters the path as drawn. Use Convert Stroke to Path if you need geometry first."),
            ("Will extra shapes in the file export too?", "Yes. Everything in the SVG is painted. The page is aimed at path-heavy files."),
        ],
        "Paste an SVG path. Click Convert path to PNG.",
    ),
    page(
        "png_use", "svg-to-png-for-email",
        "SVG to PNG for Email — Free Tool | getsvgeditor.com",
        "SVG to PNG for email. Export a 600px-wide PNG most clients will show — free browser raster.",
        "SVG to PNG for Email", "PNG for email",
        "Export at <strong>600px wide</strong> — the width email clients actually display",
        "SVG to PNG for email in SVGEditor",
        "SVG to PNG for Email",
        ["SVG to PNG for email", "600px email PNG", "SVG raster for Outlook", "Email-safe SVG export"],
        "Free online tool to convert SVG to a 600px-wide PNG for HTML email.",
        ["600px width", "Outlook-safe raster", "Transparent or as-painted", "No upload"],
        "SVG to PNG for email",
        "Rasterize at 600px for HTML email.",
        "Click Export email PNG. A 600px-wide PNG downloads for <img> in email.",
        "Export email PNG", "Export this SVG as a PNG for email",
        [
            ("Why 600px for SVG to PNG for email?", "Most marketing templates are ~600px content width. Wider PNGs get downscaled and blur in Outlook."),
            ("Do email clients render SVG?", "Many do not (Outlook). A PNG <img> is the reliable fallback."),
            ("Should email PNG be retina 3×?", "You can, but file weight hurts inbox. 600px at 1× canvas (this page) is the default; bump Custom Size if you must."),
            ("Is this the same as illustration PNG?", "No. Illustration is 1024px for web/social. Email is 600px."),
        ],
        "Paste an SVG for a newsletter. Click Export email PNG.",
    ),
    page(
        "png_asset", "svg-to-apple-touch-icon",
        "SVG to Apple Touch Icon — Free Tool | getsvgeditor.com",
        "SVG to Apple touch icon. Export a 180×180 PNG for apple-touch-icon — free browser tool.",
        "SVG to Apple Touch Icon", "Apple touch icon",
        "Export <strong>180×180</strong> for <code>apple-touch-icon</code> — not 32 favicon or 512 store tile",
        "SVG to Apple touch icon in SVGEditor",
        "SVG to Apple Touch Icon",
        ["SVG to Apple touch icon", "180x180 apple-touch-icon", "iOS home screen from SVG", "Apple touch PNG"],
        "Free online tool to convert SVG to a 180×180 Apple touch icon PNG.",
        ["180×180 canvas", "Meet into the square", "iOS home-screen size", "No upload"],
        "SVG to Apple touch icon",
        "Fit the mark into a 180×180 PNG.",
        "Click Export Apple touch icon. A 180×180 PNG downloads.",
        "Export Apple touch icon", "Export a 180×180 Apple touch icon PNG",
        [
            ("What size is SVG to Apple touch icon?", "180×180 pixels — the current apple-touch-icon size."),
            ("Should Apple touch icons be transparent?", "They can be. iOS may composite on a fill. Add a rounded rect in the SVG if you want a branded plate."),
            ("How is this different from favicon PNG?", "Favicon here is 32×32. Touch icon is 180×180 for Add to Home Screen."),
            ("Can I use 192 or 512 instead?", "PWA icons often want 192/512. Use Custom Size or 512 Pixels for those."),
        ],
        "Paste an SVG. Click Export Apple touch icon.",
    ),
    page(
        "png_res", "svg-to-png-2x-scale",
        "SVG to PNG 2x Scale — Free Tool | getsvgeditor.com",
        "SVG to PNG 2x scale. Export an @2x PNG (double the viewBox) for standard retina assets — free tool.",
        "SVG to PNG 2x Scale", "2× PNG",
        "Download an <strong>@2x</strong> PNG — half of retina @3x, not the 4× high-res pass",
        "SVG to PNG 2x scale in SVGEditor",
        "SVG to PNG 2x Scale",
        ["SVG to PNG 2x scale", "SVG @2x PNG", "Double resolution SVG raster", "2x asset from SVG"],
        "Free online tool to export SVG as a 2× scale PNG.",
        ["Exactly 2×", "Filename @2x", "Transparent canvas", "No upload"],
        "SVG to PNG 2x scale",
        "Rasterize at double the viewBox size.",
        "Click Export 2× PNG. The file is 2× the viewBox and named @2x.",
        "Export 2× PNG", "Export this SVG as a 2× PNG",
        [
            ("Is SVG to PNG 2x scale the same as the default PNG tab?", "The main PNG tab also uses 2×. This page makes that scale the titled action and names the file @2x."),
            ("When should I pick 2× instead of retina 3×?", "Android xxhdpi and older asset catalogs still want @2x. Use 3× for modern iPhone."),
            ("Does 2× stretch the graphic?", "No. Pixel size doubles; aspect stays."),
            ("Can I combine 2× with a 512 square?", "Use 512 Pixels for a square canvas. 2× follows the viewBox aspect."),
        ],
        "Paste an SVG. Click Export 2× PNG.",
    ),
    page(
        "png_input", "batch-convert-svg-to-png",
        "Batch Convert SVG to PNG — Free Tool | getsvgeditor.com",
        "Batch convert SVG to PNG. Upload or paste several <svg> roots and download a PNG for each — free tool.",
        "Batch Convert SVG to PNG", "Batch SVG → PNG",
        "Export <strong>every &lt;svg&gt; root</strong> (or multiple uploaded files) as its own PNG",
        "Batch convert SVG to PNG in SVGEditor",
        "Batch Convert SVG to PNG",
        ["Batch convert SVG to PNG", "Multiple SVG to PNG", "Bulk SVG raster", "Convert many SVGs"],
        "Free online tool to batch convert multiple SVG documents to PNG files.",
        ["Multiple <svg> roots", "Multi-file upload", "One PNG each", "No server"],
        "Batch convert SVG to PNG",
        "Rasterize each SVG in Source or each uploaded file.",
        "Click Batch export PNGs. Every <svg> block (or each uploaded file) downloads as its own PNG.",
        "Batch export PNGs", "Batch convert these SVGs to PNG",
        [
            ("How does batch convert SVG to PNG work?", "The tool finds every <svg>…</svg> in Source and downloads one PNG each. On this page Upload accepts multiple .svg files and concatenates them."),
            ("Will my browser block several downloads?", "Some browsers ask once for multiple files. Allow them, or export one-by-one if a popup blocker interferes."),
            ("Does batch zip the PNGs?", "No. Each PNG downloads separately so nothing extra is packed on the server — there is no server."),
            ("What if Source has only one SVG?", "You still get one PNG. Paste a second root or upload more files to batch."),
        ],
        "Paste several <svg> blocks or upload multiple files. Click Batch export PNGs.",
    ),
]


def main():
    assert len(PAGES) == 20, f"expected 20 pages, got {len(PAGES)}"
    questions = [q for p in PAGES for q, _ in p["faqs"]]
    dups = sorted({q for q in questions if questions.count(q) > 1})
    assert len(questions) == len(set(questions)), f"duplicate FAQ questions: {dups}"
    for p in PAGES:
        assert len(p["faqs"]) == 4, p["slug"]
        assert 2 <= len(p["guides"]) <= 4, (p["slug"], len(p["guides"]))
        build_page(p)
    slugs_path = Path(__file__).resolve().parent / "_png_intent_slugs.txt"
    slugs_path.write_text("\n".join(p["slug"] for p in PAGES) + "\n", encoding="utf-8")
    print("wrote", slugs_path)
    print("done", len(PAGES))


if __name__ == "__main__":
    main()
