#!/usr/bin/env python3
"""Generate SEO tool pages for aspect / svelte / react-native (ASR) clusters."""
from pathlib import Path

from tool_page_builder import build_page, note, guides

ROOT = Path(__file__).resolve().parent.parent

CLUSTERS = {
    "aspect": [
        "/fix-svg-gradient-stretch-in-flexbox",
        "/fix-svg-gradient-stretch-in-css-grid",
        "/set-svg-preserveaspectratio-for-flexbox",
        "/svg-gradient-objectboundingbox-stretch-fix",
        "/set-svg-preserveaspectratio-online",
        "/svg-preserveaspectratio-meet-slice-none",
    ],
    "svelte": [
        "/svg-to-svelte",
        "/svg-to-svelte-typescript",
        "/svg-to-svelte-single-file-component",
        "/svg-icon-to-svelte",
        "/svg-to-sveltekit",
    ],
    "rn_hub": [
        "/svg-to-react-native",
        "/svg-to-react-native-svg-component",
        "/svg-to-react-native-jsx",
        "/paste-svg-to-react-native-online",
        "/svg-react-native-component-generator",
        "/svg-to-react-native-typescript",
        "/svg-to-react-native-functional-component",
        "/svg-to-react-native-forwardref-component",
    ],
    "rn_assets": [
        "/svg-icon-to-react-native",
        "/convert-svg-icon-to-react-native-svg",
        "/figma-svg-to-react-native",
        "/convert-figma-svg-export-to-react-native",
        "/svg-logo-to-react-native",
        "/svg-illustration-to-react-native",
    ],
    "rn_platform": [
        "/svg-to-expo-react-native",
        "/convert-svg-to-expo-svg-component",
        "/svg-to-react-native-android",
        "/svg-to-react-native-ios",
    ],
    "rn_xml": [
        "/svg-to-svgxml-react-native",
        "/svg-string-to-react-native-component",
        "/inline-svg-to-react-native-svg",
    ],
    "rn_elements": [
        "/svg-path-to-react-native",
        "/convert-svg-path-to-react-native-svg-path",
        "/svg-circle-to-react-native",
        "/svg-rect-to-react-native",
        "/convert-svg-lineargradient-to-react-native",
    ],
    "rn_props": [
        "/convert-svg-attributes-to-react-native-props",
        "/camelcase-svg-attributes-for-react-native",
        "/svg-to-react-native-currentcolor",
        "/convert-svg-fill-to-color-prop-react-native",
        "/svg-icon-with-size-props-react-native",
        "/responsive-svg-icon-react-native-component",
        "/svg-to-react-native-with-viewbox",
    ],
    "rn_clean": [
        "/optimize-svg-for-react-native",
        "/remove-unsupported-svg-for-react-native",
        "/svgr-native-svg-to-react-native-online",
    ],
}

LABEL = {
    "/fix-svg-gradient-stretch-in-flexbox": "Fix gradient Flexbox",
    "/fix-svg-gradient-stretch-in-css-grid": "Fix gradient Grid",
    "/set-svg-preserveaspectratio-for-flexbox": "Aspect for Flexbox",
    "/svg-gradient-objectboundingbox-stretch-fix": "objectBoundingBox fix",
    "/set-svg-preserveaspectratio-online": "Set preserveAspectRatio",
    "/svg-preserveaspectratio-meet-slice-none": "Meet / slice / none",
    "/svg-to-svelte": "SVG to Svelte",
    "/svg-to-svelte-typescript": "Svelte TypeScript",
    "/svg-to-svelte-single-file-component": "Svelte SFC",
    "/svg-icon-to-svelte": "Icon to Svelte",
    "/svg-to-sveltekit": "SVG to SvelteKit",
    "/svg-to-react-native": "SVG to RN",
    "/svg-to-react-native-svg-component": "RN SVG component",
    "/svg-to-react-native-jsx": "RN JSX",
    "/paste-svg-to-react-native-online": "Paste SVG to RN",
    "/svg-react-native-component-generator": "RN component generator",
    "/svg-to-react-native-typescript": "RN TypeScript",
    "/svg-icon-to-react-native": "Icon to RN",
    "/convert-svg-icon-to-react-native-svg": "Icon to RN SVG",
    "/figma-svg-to-react-native": "Figma SVG to RN",
    "/convert-figma-svg-export-to-react-native": "Figma export to RN",
    "/svg-logo-to-react-native": "Logo to RN",
    "/svg-illustration-to-react-native": "Illustration to RN",
    "/svg-to-expo-react-native": "SVG to Expo",
    "/convert-svg-to-expo-svg-component": "Expo SVG component",
    "/svg-to-react-native-android": "RN Android",
    "/svg-to-react-native-ios": "RN iOS",
    "/svg-to-svgxml-react-native": "SvgXml RN",
    "/svg-string-to-react-native-component": "SVG string to RN",
    "/inline-svg-to-react-native-svg": "Inline SVG to RN",
    "/svg-path-to-react-native": "Path to RN",
    "/convert-svg-path-to-react-native-svg-path": "Path to RN Path",
    "/svg-circle-to-react-native": "Circle to RN",
    "/svg-rect-to-react-native": "Rect to RN",
    "/convert-svg-lineargradient-to-react-native": "LinearGradient RN",
    "/convert-svg-attributes-to-react-native-props": "Attrs to RN props",
    "/camelcase-svg-attributes-for-react-native": "CamelCase attrs",
    "/svg-to-react-native-currentcolor": "RN currentColor",
    "/convert-svg-fill-to-color-prop-react-native": "Fill to color prop",
    "/svg-icon-with-size-props-react-native": "RN size props",
    "/responsive-svg-icon-react-native-component": "Responsive RN icon",
    "/svg-to-react-native-with-viewbox": "RN with viewBox",
    "/optimize-svg-for-react-native": "Optimize for RN",
    "/remove-unsupported-svg-for-react-native": "Remove unsupported",
    "/svgr-native-svg-to-react-native-online": "SVGR Native online",
    "/svg-to-react-native-functional-component": "RN functional",
    "/svg-to-react-native-forwardref-component": "RN forwardRef",
}


def cluster_guides(cluster, slug):
    hrefs = [h for h in CLUSTERS[cluster] if h != f"/{slug}"]
    return guides([(h, LABEL[h]) for h in hrefs[:4]])


def cluster_note(cluster, slug):
    hrefs = [h for h in CLUSTERS[cluster] if h != f"/{slug}"]
    if len(hrefs) < 2:
        raise ValueError(f"cluster_note needs 2 links for {cluster}/{slug}")
    a, b = hrefs[0], hrefs[1]
    return note(a, LABEL[a], b, LABEL[b])


def page(
    family,
    cluster,
    slug,
    title,
    description,
    h1,
    crumb,
    sub,
    og_alt,
    app_name,
    app_alts,
    app_desc,
    features,
    howto_name,
    howto_desc,
    howto_click,
    btn,
    btn_title,
    faqs,
    empty,
):
    return {
        "family": family,
        "cluster": cluster,
        "slug": slug,
        "title": title,
        "description": description,
        "h1": h1,
        "crumb": crumb,
        "sub": sub,
        "og_alt": og_alt,
        "app_name": app_name,
        "app_alts": app_alts,
        "app_desc": app_desc,
        "features": features,
        "howto_name": howto_name,
        "howto_desc": howto_desc,
        "howto_click": howto_click,
        "btn": btn,
        "btn_title": btn_title,
        "faq_aria": f"{h1} FAQ",
        "faqs": faqs,
        "note_html": cluster_note(cluster, slug),
        "guides": cluster_guides(cluster, slug),
        "empty": empty,
    }


PAGES = [
    page(
        "aspect", "aspect", "fix-svg-gradient-stretch-in-flexbox",
        "Fix SVG Gradient Stretch in Flexbox Online — Free Tool | getsvgeditor.com",
        "Fix SVG gradient stretch in Flexbox online. Correct preserveAspectRatio and gradientUnits so fills stop distorting — free browser tool, no upload.",
        "Fix SVG Gradient Stretch in Flexbox", "Fix gradient flexbox",
        "Stop <strong>gradient stretch</strong> when SVG sits in a Flexbox row or column",
        "Fix SVG gradient stretch in Flexbox in SVGEditor",
        "Fix SVG Gradient Stretch in Flexbox",
        ["Fix SVG gradient Flexbox", "SVG gradient stretch Flexbox fix", "Flexbox SVG gradient distortion", "Online Flexbox SVG gradient tool"],
        "Free online tool to fix SVG gradient stretch inside Flexbox layouts. Adjust aspect and gradient settings with live preview.",
        ["Flexbox-aware aspect fix", "Gradient stretch correction", "Live preview", "No upload"],
        "Fix SVG gradient stretch in Flexbox",
        "Correct preserveAspectRatio and related attributes so gradients keep shape in Flexbox.",
        "Click Fix Flexbox stretch. Aspect and gradient settings update for Flexbox layouts.",
        "Fix gradient stretch", "Fix SVG gradient stretch in Flexbox",
        [
            ("How do I fix an SVG gradient that stretches in Flexbox?", "Paste the SVG and click Fix gradient stretch. preserveAspectRatio and gradient framing update so the fill no longer distorts in a flex item."),
            ("Why do gradients stretch inside flex containers?", "Flex sizing can change the SVG viewport while gradientUnits stay objectBoundingBox, so paints scale unevenly with the box."),
            ("Need the same fix for CSS Grid instead of Flexbox?", "Open Fix SVG Gradient Stretch in CSS Grid for grid-specific framing."),
            ("Is fixing Flexbox gradient stretch free without uploading?", "Yes. Everything runs in your browser — free, no upload."),
        ],
        "Paste an SVG that stretches in Flexbox. Click Fix gradient stretch.",
    ),
    page(
        "aspect", "aspect", "fix-svg-gradient-stretch-in-css-grid",
        "Fix SVG Gradient Stretch in CSS Grid Online — Free Tool | getsvgeditor.com",
        "Fix SVG gradient stretch in CSS Grid online. Keep gradient fills proportional inside grid cells — free, in your browser, no upload.",
        "Fix SVG Gradient Stretch in CSS Grid", "Fix gradient grid",
        "Correct <strong>gradient stretch</strong> when SVG fills a CSS Grid cell",
        "Fix SVG gradient stretch in CSS Grid in SVGEditor",
        "Fix SVG Gradient Stretch in CSS Grid",
        ["Fix SVG gradient CSS Grid", "SVG gradient stretch grid fix", "Grid cell SVG gradient", "Online CSS Grid SVG gradient tool"],
        "Free online tool to fix SVG gradient stretch in CSS Grid layouts with live preview.",
        ["Grid-aware aspect fix", "Gradient stretch correction", "Live preview", "No upload"],
        "Fix SVG gradient stretch in CSS Grid",
        "Adjust aspect and gradient attributes so paints stay proportional in grid cells.",
        "Click Fix Grid stretch. Aspect and gradient settings update for CSS Grid.",
        "Fix Grid stretch", "Fix SVG gradient stretch in CSS Grid",
        [
            ("How can I stop SVG gradients from stretching in CSS Grid?", "Paste markup and click Fix Grid stretch to rebalance preserveAspectRatio and gradient framing for grid cells."),
            ("Does objectBoundingBox behave differently in grid tracks?", "Yes. Track sizing changes the bounding box, which can skew objectBoundingBox gradients unless aspect is locked."),
            ("Looking for a Flexbox-focused gradient stretch fix?", "Use Fix SVG Gradient Stretch in Flexbox for flex layouts."),
            ("Do I upload files to fix grid gradient stretch?", "No — free local browser tool."),
        ],
        "Paste an SVG stretched in a grid cell. Click Fix Grid stretch.",
    ),
    page(
        "aspect", "aspect", "set-svg-preserveaspectratio-for-flexbox",
        "Set SVG preserveAspectRatio for Flexbox Online — Free | getsvgeditor.com",
        "Set SVG preserveAspectRatio for Flexbox online. Choose meet, slice, or none for flex items — free live preview, no upload.",
        "Set SVG preserveAspectRatio for Flexbox", "preserveAspectRatio Flexbox",
        "Write the right <code>preserveAspectRatio</code> value for Flexbox layouts",
        "Set SVG preserveAspectRatio for Flexbox in SVGEditor",
        "Set SVG preserveAspectRatio for Flexbox",
        ["preserveAspectRatio Flexbox", "Set SVG aspect Flexbox", "Flexbox SVG preserveAspectRatio", "Online Flexbox aspect ratio SVG"],
        "Free online tool to set SVG preserveAspectRatio optimized for Flexbox embedding.",
        ["Flexbox-oriented aspect values", "meet / slice / none", "Live preview", "No upload"],
        "Set preserveAspectRatio for Flexbox",
        "Apply a Flexbox-friendly preserveAspectRatio on the SVG root.",
        "Click Set Flexbox aspect. preserveAspectRatio updates for flex items.",
        "Set Flexbox aspect", "Set preserveAspectRatio for Flexbox",
        [
            ("How do I set preserveAspectRatio for an SVG used in Flexbox?", "Paste the SVG and click Set Flexbox aspect to write a Flexbox-friendly preserveAspectRatio."),
            ("Should Flexbox icons use meet or slice?", "meet letterboxes to fit; slice crops to fill. Pick based on whether clipping is acceptable."),
            ("Want a general meet/slice/none explainer tool?", "Open SVG preserveAspectRatio Meet Slice None to compare modes."),
            ("Does setting preserveAspectRatio require uploading?", "No — free browser-only tool."),
        ],
        "Paste SVG for a flex item. Click Set Flexbox aspect.",
    ),
    page(
        "aspect", "aspect", "svg-gradient-objectboundingbox-stretch-fix",
        "SVG Gradient objectBoundingBox Stretch Fix Online — Free | getsvgeditor.com",
        "Fix SVG gradient objectBoundingBox stretch online. Correct gradientUnits and aspect so paints stop warping — free, no upload.",
        "SVG Gradient objectBoundingBox Stretch Fix", "objectBoundingBox fix",
        "Repair stretch caused by <code>gradientUnits=\"objectBoundingBox\"</code>",
        "SVG gradient objectBoundingBox stretch fix in SVGEditor",
        "SVG Gradient objectBoundingBox Stretch Fix",
        ["objectBoundingBox gradient stretch", "Fix SVG gradientUnits stretch", "objectBoundingBox paint fix", "Online objectBoundingBox SVG tool"],
        "Free online tool to fix SVG gradients that stretch under objectBoundingBox units.",
        ["objectBoundingBox-aware fix", "gradientUnits guidance", "Live preview", "No upload"],
        "Fix objectBoundingBox gradient stretch",
        "Adjust gradientUnits and aspect so objectBoundingBox paints stay proportional.",
        "Click Fix objectBoundingBox. Gradient framing updates to stop stretch.",
        "Fix objectBoundingBox", "Fix objectBoundingBox gradient stretch",
        [
            ("How do I fix objectBoundingBox gradient stretch in SVG?", "Paste markup and click Fix objectBoundingBox to rebalance gradientUnits and aspect framing."),
            ("Why does objectBoundingBox warp linear gradients?", "It maps the gradient to the element's bounding box, so non-square boxes stretch the paint."),
            ("Need a Grid-specific linear-gradient stretch stop?", "Try Stop SVG Linear Gradient From Stretching in Grid."),
            ("Is the objectBoundingBox fix free in the browser?", "Yes — free, no upload."),
        ],
        "Paste SVG with stretched objectBoundingBox gradients. Click Fix objectBoundingBox.",
    ),
    page(
        "aspect", "aspect", "set-svg-preserveaspectratio-online",
        "Set SVG preserveAspectRatio Online — Free Tool | getsvgeditor.com",
        "Set SVG preserveAspectRatio online. Edit meet, slice, or none with live preview — free browser tool, no upload.",
        "Set SVG preserveAspectRatio Online", "Set preserveAspectRatio",
        "Edit the root <code>preserveAspectRatio</code> attribute with live preview",
        "Set SVG preserveAspectRatio online in SVGEditor",
        "Set SVG preserveAspectRatio Online",
        ["Set preserveAspectRatio online", "Edit SVG preserveAspectRatio", "SVG aspect ratio attribute", "Online preserveAspectRatio tool"],
        "Free online tool to set or change the SVG preserveAspectRatio attribute.",
        ["Edit preserveAspectRatio", "Live preview", "Editable source", "No upload"],
        "Set SVG preserveAspectRatio",
        "Write or update the preserveAspectRatio attribute on the SVG root.",
        "Click Set preserveAspectRatio. The root attribute updates and preview refreshes.",
        "Set preserveAspectRatio", "Set SVG preserveAspectRatio",
        [
            ("How do I set preserveAspectRatio on an SVG online?", "Paste the SVG and click Set preserveAspectRatio to write the root attribute."),
            ("What values can preserveAspectRatio take?", "Common values combine an alignment like xMidYMid with meet, slice, or none."),
            ("Need Flexbox-specific preserveAspectRatio defaults?", "Use Set SVG preserveAspectRatio for Flexbox."),
            ("Is setting preserveAspectRatio free and private?", "Yes — free, no upload."),
        ],
        "Paste SVG missing or wrong preserveAspectRatio. Click Set preserveAspectRatio.",
    ),
    page(
        "aspect", "aspect", "svg-preserveaspectratio-meet-slice-none",
        "SVG preserveAspectRatio Meet Slice None Online — Free | getsvgeditor.com",
        "Compare SVG preserveAspectRatio meet, slice, and none online. Preview scaling modes instantly — free, no upload.",
        "SVG preserveAspectRatio Meet, Slice, None", "Meet slice none",
        "Preview <strong>meet</strong>, <strong>slice</strong>, and <strong>none</strong> scaling side by side",
        "SVG preserveAspectRatio meet slice none in SVGEditor",
        "SVG preserveAspectRatio Meet Slice None",
        ["preserveAspectRatio meet slice none", "SVG meet vs slice", "SVG none scaling", "Online meet slice none tool"],
        "Free online tool to compare SVG preserveAspectRatio meet, slice, and none modes.",
        ["meet / slice / none preview", "Clear scaling differences", "Live preview", "No upload"],
        "Compare meet, slice, and none",
        "Apply and preview preserveAspectRatio meet, slice, or none.",
        "Click Apply scaling mode. Preview shows meet, slice, or none behavior.",
        "Apply scaling mode", "Apply preserveAspectRatio meet, slice, or none",
        [
            ("What is the difference between meet, slice, and none in SVG?", "meet fits inside the viewport; slice fills and may crop; none ignores aspect and can distort."),
            ("When should I choose slice over meet?", "Use slice when you want the graphic to fill the box and cropping is acceptable."),
            ("Want to fill a container without distortion after picking a mode?", "Open Set SVG preserveAspectRatio Online."),
            ("Is comparing meet/slice/none free in the browser?", "Yes. Free, no upload."),
        ],
        "Paste SVG. Click Apply scaling mode to preview meet, slice, or none.",
    ),
    page(
        "svelte", "svelte", "svg-to-svelte",
        "SVG to Svelte Converter Online — Free Tool | getsvgeditor.com",
        "Convert SVG to Svelte online. Turn markup into a Svelte component — free, in your browser, no upload.",
        "SVG to Svelte", "SVG to Svelte",
        "Convert SVG markup into a reusable <strong>Svelte</strong> component",
        "SVG to Svelte converter in SVGEditor",
        "SVG to Svelte",
        ["SVG to Svelte", "Convert SVG Svelte component", "SVG Svelte converter", "Online SVG to Svelte"],
        "Free online SVG to Svelte converter. Paste SVG and generate a Svelte component in the browser.",
        ["Svelte component output", "Live SVG preview", "Editable source", "No upload"],
        "Convert SVG to Svelte",
        "Turn SVG markup into a Svelte component.",
        "Click Convert to Svelte. Component-ready output is prepared from the SVG.",
        "Convert to Svelte", "Convert this SVG to a Svelte component",
        [
            ("How do I convert an SVG into a Svelte component?", "Paste the SVG and click Convert to Svelte. Copy the component output for your project."),
            ("Do you support TypeScript Svelte components?", "Yes. Open SVG to Svelte TypeScript for typed .svelte output."),
            ("Can I target a single-file Svelte component structure?", "Use SVG to Svelte Single File Component for SFC-oriented output."),
            ("Is SVG to Svelte conversion free without uploading?", "Yes. Free browser tool."),
        ],
        "Paste an icon SVG. Click Convert to Svelte.",
    ),
    page(
        "svelte", "svelte", "svg-to-svelte-typescript",
        "SVG to Svelte TypeScript Online — Free Tool | getsvgeditor.com",
        "Convert SVG to Svelte TypeScript online. Generate typed Svelte components — free, no upload.",
        "SVG to Svelte TypeScript", "Svelte TypeScript",
        "Emit a <strong>TypeScript</strong> Svelte component from SVG",
        "SVG to Svelte TypeScript in SVGEditor",
        "SVG to Svelte TypeScript",
        ["SVG to Svelte TypeScript", "Svelte TS SVG component", "Typed Svelte SVG", "Online SVG Svelte TS"],
        "Free online tool to convert SVG into TypeScript Svelte components.",
        ["TypeScript Svelte output", "Live preview", "Editable markup", "No upload"],
        "Convert SVG to Svelte TypeScript",
        "Generate a typed Svelte component from SVG.",
        "Click Convert to Svelte TS. TypeScript component output is prepared.",
        "Convert to Svelte TS", "Convert SVG to a Svelte TypeScript component",
        [
            ("How do I get a Svelte TypeScript component from SVG?", "Paste SVG and click Convert to Svelte TS, then copy the typed component."),
            ("Does the TS output work with lang=\"ts\" script blocks?", "Yes. Output is oriented toward TypeScript script sections in .svelte files."),
            ("Building for SvelteKit with TypeScript?", "Pair with SVG to SvelteKit for Kit-oriented structure."),
            ("Is Svelte TS conversion private and free?", "Yes — free, no upload."),
        ],
        "Paste SVG. Click Convert to Svelte TS.",
    ),
    page(
        "svelte", "svelte", "svg-to-svelte-single-file-component",
        "SVG to Svelte Single File Component — Free Tool | getsvgeditor.com",
        "Convert SVG to a Svelte SFC online. Produce .svelte single-file components — free, in your browser.",
        "SVG to Svelte Single File Component", "Svelte SFC",
        "Output a <strong>.svelte</strong> single-file component from SVG",
        "SVG to Svelte single file component in SVGEditor",
        "SVG to Svelte Single File Component",
        ["SVG to Svelte SFC", "Svelte single file component SVG", ".svelte from SVG", "Online Svelte SFC converter"],
        "Free online converter from SVG to Svelte single-file components.",
        ["SFC .svelte structure", "Live preview", "Editable source", "No upload"],
        "Convert SVG to a Svelte SFC",
        "Generate a .svelte single-file component from SVG.",
        "Click Convert to Svelte SFC. Single-file component output is prepared.",
        "Convert to Svelte SFC", "Convert SVG to a Svelte single-file component",
        [
            ("How do I turn SVG into a .svelte SFC?", "Paste the SVG and click Convert to Svelte SFC, then copy the single-file component."),
            ("Does SFC output include markup for the SVG in the template?", "Yes. The SVG lands in the component markup section."),
            ("Need icon-sized Svelte output?", "Open SVG Icon to Svelte for compact icon components."),
            ("Is Svelte SFC conversion private?", "Yes. Free, no upload."),
        ],
        "Paste SVG. Click Convert to Svelte SFC.",
    ),
    page(
        "svelte", "svelte", "svg-icon-to-svelte",
        "SVG Icon to Svelte Online — Free Tool | getsvgeditor.com",
        "Convert SVG icons to Svelte online. Build compact icon components — free, no upload.",
        "SVG Icon to Svelte", "Icon to Svelte",
        "Turn an <strong>icon SVG</strong> into a compact Svelte component",
        "SVG icon to Svelte in SVGEditor",
        "SVG Icon to Svelte",
        ["SVG icon to Svelte", "Svelte icon component from SVG", "Convert icon SVG Svelte", "Online icon to Svelte"],
        "Free online tool to convert SVG icons into Svelte components.",
        ["Icon-sized Svelte output", "Live preview", "Editable source", "No upload"],
        "Convert an SVG icon to Svelte",
        "Generate a compact Svelte icon component from SVG.",
        "Click Convert icon to Svelte. A compact icon component is prepared.",
        "Convert icon to Svelte", "Convert this SVG icon to Svelte",
        [
            ("How do I convert an SVG icon into Svelte?", "Paste the icon and click Convert icon to Svelte for a compact component."),
            ("Should icons use currentColor for theming in Svelte?", "Often yes — ensure fills use currentColor before converting when you want CSS color control."),
            ("Need SvelteKit routing or app structure instead?", "Open SVG to SvelteKit for Kit-oriented output."),
            ("Is icon-to-Svelte conversion free?", "Yes — free, browser-only."),
        ],
        "Paste an icon SVG. Click Convert icon to Svelte.",
    ),
    page(
        "svelte", "svelte", "svg-to-sveltekit",
        "SVG to SvelteKit Online — Free Tool | getsvgeditor.com",
        "Convert SVG to SvelteKit online. Generate components ready for SvelteKit apps — free browser tool, no upload.",
        "SVG to SvelteKit", "SVG to SvelteKit",
        "Prepare SVG as a component for <strong>SvelteKit</strong> projects",
        "SVG to SvelteKit in SVGEditor",
        "SVG to SvelteKit",
        ["SVG to SvelteKit", "SvelteKit SVG component", "Convert SVG SvelteKit", "Online SVG to SvelteKit"],
        "Free online tool to convert SVG into SvelteKit-friendly components.",
        ["SvelteKit-oriented output", "Live preview", "Editable markup", "No upload"],
        "Convert SVG to SvelteKit",
        "Generate a Svelte component structured for SvelteKit apps.",
        "Click Convert to SvelteKit. Kit-friendly component output is prepared.",
        "Convert to SvelteKit", "Convert SVG to a SvelteKit component",
        [
            ("Can I convert SVG for use in a SvelteKit app?", "Yes. Paste SVG and click Convert to SvelteKit for Kit-oriented component output."),
            ("Is SvelteKit output different from plain Svelte?", "Slightly — naming and structure lean toward SvelteKit app folders; core markup is still Svelte."),
            ("Want TypeScript in your SvelteKit icons?", "Combine with SVG to Svelte TypeScript."),
            ("Does SvelteKit conversion require uploading?", "No. Free local tool."),
        ],
        "Paste SVG. Click Convert to SvelteKit.",
    ),
    page(
        "rn", "rn_hub", "svg-to-react-native",
        "SVG to React Native Converter Online — Free Tool | getsvgeditor.com",
        "Convert SVG to React Native online. Turn markup into react-native-svg components — free, in your browser, no upload.",
        "SVG to React Native", "SVG to RN",
        "Convert SVG into a <strong>react-native-svg</strong> component",
        "SVG to React Native converter in SVGEditor",
        "SVG to React Native",
        ["SVG to React Native", "Convert SVG React Native", "SVG RN converter", "Online SVG to RN"],
        "Free online SVG to React Native converter. Paste SVG and generate react-native-svg output in the browser.",
        ["react-native-svg output", "Live SVG preview", "Editable source", "No upload"],
        "Convert SVG to React Native",
        "Turn SVG markup into a React Native SVG component.",
        "Click Convert to RN. react-native-svg component output is prepared.",
        "Convert to RN", "Convert this SVG to React Native",
        [
            ("How do I convert an SVG into React Native?", "Paste the SVG and click Convert to RN. Copy the react-native-svg component for your app."),
            ("Does this target react-native-svg specifically?", "Yes. For a library-focused path, open SVG to react-native-svg Component."),
            ("Can I paste SVG without downloading a file first?", "Yes — use Paste SVG to React Native Online for a paste-first workflow."),
            ("Is SVG to React Native conversion free without uploading?", "Yes. Free browser tool."),
        ],
        "Paste an icon SVG. Click Convert to RN.",
    ),
    page(
        "rn", "rn_hub", "svg-to-react-native-svg-component",
        "SVG to React Native SVG Component Online — Free | getsvgeditor.com",
        "Convert SVG to a React Native SVG component online. Export a ready-to-import RN SVG component — free browser tool.",
        "SVG to React Native SVG Component", "RN SVG component",
        "Export a ready-to-import <strong>RN SVG component</strong> from SVG",
        "SVG to React Native SVG component in SVGEditor",
        "SVG to React Native SVG Component",
        ["SVG to RN SVG component", "react-native-svg component", "RN SVG component from SVG", "Online RN SVG component"],
        "Free online tool to turn SVG into an importable react-native-svg component.",
        ["Importable RN SVG component", "Live preview", "Editable markup", "No upload"],
        "Convert SVG to an RN SVG component",
        "Generate an importable React Native SVG component from SVG.",
        "Click Make RN SVG component. Import-ready component output is prepared.",
        "Make RN SVG component", "SVG to react-native-svg Component component",
        [
            ("How do I get a React Native SVG component from SVG?", "Paste the SVG and click Make RN SVG component, then copy the component file."),
            ("Is this the same as a generic RN component convert?", "This page focuses on react-native-svg component shape; SVG React Native Component Generator is the broader component wording."),
            ("Need JSX-only output without a full component shell?", "Open SVG to React Native JSX."),
            ("Does RN SVG component conversion upload SVG?", "No — free local tool."),
        ],
        "Paste SVG. Click Make RN SVG component.",
    ),
    page(
        "rn", "rn_hub", "svg-to-react-native-jsx",
        "SVG to React Native JSX Online — Free Tool | getsvgeditor.com",
        "Convert SVG to React Native JSX online. Emit JSX for react-native-svg — free browser tool, no upload.",
        "SVG to React Native JSX", "RN JSX",
        "Emit <strong>JSX</strong> suitable for react-native-svg trees",
        "SVG to React Native JSX in SVGEditor",
        "SVG to React Native JSX",
        ["SVG to React Native JSX", "RN SVG JSX", "react-native-svg JSX", "Online SVG RN JSX"],
        "Free online tool to convert SVG into React Native JSX output.",
        ["RN JSX output", "Live preview", "Editable markup", "No upload"],
        "Convert SVG to React Native JSX",
        "Generate JSX for React Native SVG from markup.",
        "Click Convert to RN JSX. JSX output is prepared from the SVG.",
        "Convert to RN JSX", "Convert this SVG to React Native JSX",
        [
            ("Can I convert SVG paths into React Native JSX?", "Yes. Paste SVG and click Convert to RN JSX for JSX-friendly output."),
            ("Is JSX better than a full component for icons?", "Teams embedding icons inline often prefer JSX; libraries usually wrap a component."),
            ("Looking for a paste-and-go online converter?", "Use Paste SVG to React Native Online."),
            ("Does RN JSX conversion require uploading?", "No — free local tool."),
        ],
        "Paste SVG. Click Convert to RN JSX.",
    ),
    page(
        "rn", "rn_hub", "paste-svg-to-react-native-online",
        "Paste SVG to React Native Online — Free Tool | getsvgeditor.com",
        "Paste SVG to React Native online. Drop markup in the browser and get RN output — free, no upload.",
        "Paste SVG to React Native Online", "Paste SVG to RN",
        "<strong>Paste SVG</strong> in the browser and convert straight to React Native",
        "Paste SVG to React Native online in SVGEditor",
        "Paste SVG to React Native Online",
        ["Paste SVG to React Native", "Paste SVG RN online", "Clipboard SVG to RN", "Online paste SVG React Native"],
        "Free online tool to paste SVG and convert it to React Native without uploading files.",
        ["Paste-first workflow", "RN conversion", "Live preview", "No upload"],
        "Paste SVG and convert to React Native",
        "Paste SVG markup and convert it to React Native output.",
        "Click Convert pasted SVG. RN output is prepared from the pasted markup.",
        "Convert pasted SVG", "Convert pasted SVG to React Native",
        [
            ("Can I paste SVG code and convert it to React Native online?", "Yes. Paste into the editor and click Convert pasted SVG — no file upload needed."),
            ("Why use paste-first instead of a file converter?", "Paste is faster for snippets from Figma, Slack, or Source when you do not have a saved .svg."),
            ("Want a full component generator after pasting?", "Open SVG React Native Component Generator next."),
            ("Is paste-to-RN free and private?", "Yes. Free, browser-local."),
        ],
        "Paste SVG markup. Click Convert pasted SVG.",
    ),
    page(
        "rn", "rn_hub", "svg-react-native-component-generator",
        "SVG React Native Component Generator Online — Free | getsvgeditor.com",
        "Generate React Native components from SVG online. Component-generator workflow for RN SVG — free, no upload.",
        "SVG React Native Component Generator", "RN component generator",
        "Use a <strong>component generator</strong> flow from SVG to React Native",
        "SVG React Native component generator in SVGEditor",
        "SVG React Native Component Generator",
        ["SVG RN component generator", "Generate React Native SVG component", "RN SVG generator online", "Online SVG RN generator"],
        "Free online SVG React Native component generator. Paste SVG and generate a component.",
        ["Generator-style RN output", "Live preview", "Editable source", "No upload"],
        "Generate a React Native component from SVG",
        "Generate a React Native component from SVG using a generator workflow.",
        "Click Generate RN component. Generated component output is prepared.",
        "Generate RN component", "Generate a React Native component from SVG",
        [
            ("How does the SVG React Native component generator work?", "Paste SVG and click Generate RN component to produce a generated component shell."),
            ("When is a generator better than a simple convert?", "Generators emphasize scaffolded props and structure; simple convert focuses on markup mapping."),
            ("Need TypeScript generated components?", "Continue with SVG to React Native TypeScript."),
            ("Does the generator upload my SVG?", "No — free local tool."),
        ],
        "Paste SVG. Click Generate RN component.",
    ),
    page(
        "rn", "rn_hub", "svg-to-react-native-typescript",
        "SVG to React Native TypeScript Online — Free Tool | getsvgeditor.com",
        "Convert SVG to React Native TypeScript online. Generate typed RN SVG components — free, no upload.",
        "SVG to React Native TypeScript", "RN TypeScript",
        "Emit a <strong>TypeScript</strong> React Native SVG component from SVG",
        "SVG to React Native TypeScript in SVGEditor",
        "SVG to React Native TypeScript",
        ["SVG to RN TypeScript", "Typed React Native SVG", "RN TS SVG component", "Online SVG RN TypeScript"],
        "Free online tool to convert SVG into TypeScript React Native SVG components.",
        ["TypeScript RN output", "Live preview", "Editable markup", "No upload"],
        "Convert SVG to React Native TypeScript",
        "Generate a typed React Native SVG component from SVG.",
        "Click Convert to RN TS. TypeScript component output is prepared.",
        "Convert to RN TS", "Convert SVG to React Native TypeScript",
        [
            ("How do I get a TypeScript React Native SVG component from SVG?", "Paste SVG and click Convert to RN TS, then copy the typed component."),
            ("Need a functional-component style export?", "Open SVG to React Native Functional Component."),
            ("Prefer a generator-style RN component flow?", "Try SVG React Native Component Generator."),
            ("Is RN TypeScript conversion private and free?", "Yes — free, no upload."),
        ],
        "Paste SVG. Click Convert to RN TS.",
    ),
    page(
        "rn", "rn_assets", "svg-icon-to-react-native",
        "SVG Icon to React Native Online — Free Tool | getsvgeditor.com",
        "Convert SVG icons to React Native online. Build compact RN icon components — free, no upload.",
        "SVG Icon to React Native", "Icon to RN",
        "Turn an <strong>icon SVG</strong> into a compact React Native component",
        "SVG icon to React Native in SVGEditor",
        "SVG Icon to React Native",
        ["SVG icon to React Native", "RN icon from SVG", "Convert icon SVG RN", "Online icon to RN"],
        "Free online tool to convert SVG icons into React Native components.",
        ["Icon-sized RN output", "Live preview", "Editable source", "No upload"],
        "Convert an SVG icon to React Native",
        "Generate a compact React Native icon component from SVG.",
        "Click Convert icon to RN. A compact icon component is prepared.",
        "Convert icon to RN", "Convert this SVG icon to React Native",
        [
            ("How do I convert an SVG icon into React Native?", "Paste the icon and click Convert icon to RN for a compact component."),
            ("Should icons expose size props in RN?", "Often yes — continue with SVG Icon With Size Props React Native."),
            ("Need react-native-svg-specific icon mapping?", "Open Convert SVG Icon to React Native SVG."),
            ("Is icon-to-RN conversion free?", "Yes — free, browser-only."),
        ],
        "Paste an icon SVG. Click Convert icon to RN.",
    ),
    page(
        "rn", "rn_assets", "convert-svg-icon-to-react-native-svg",
        "Convert SVG Icon to React Native SVG Online — Free | getsvgeditor.com",
        "Convert SVG icons to react-native-svg online. Map icon markup to RN SVG elements — free browser tool.",
        "Convert SVG Icon to React Native SVG", "Icon to RN SVG",
        "Map an <strong>icon SVG</strong> onto react-native-svg elements",
        "Convert SVG icon to react-native-svg in SVGEditor",
        "Convert SVG Icon to React Native SVG",
        ["Convert SVG icon to RN SVG", "Icon to react-native-svg", "RN SVG icon converter", "Online icon RN SVG"],
        "Free online tool to convert SVG icons into react-native-svg trees.",
        ["Icon → react-native-svg", "Live preview", "Editable markup", "No upload"],
        "Convert an SVG icon to react-native-svg",
        "Transform icon SVG into react-native-svg element output.",
        "Click Convert icon RN SVG. Icon-mapped RN SVG output is prepared.",
        "Convert icon RN SVG", "Convert SVG icon to react-native-svg",
        [
            ("How do I convert an SVG icon to react-native-svg?", "Paste the icon and click Convert icon RN SVG to map it for the RN SVG library."),
            ("How is this different from SVG Icon to React Native?", "This page stresses react-native-svg element mapping; the other is the broader icon-to-RN entry."),
            ("Want currentColor theming on icons?", "Use SVG to React Native currentColor before converting."),
            ("Does icon RN SVG conversion upload files?", "No. Free local tool."),
        ],
        "Paste an icon SVG. Click Convert icon RN SVG.",
    ),
    page(
        "rn", "rn_assets", "figma-svg-to-react-native",
        "Figma SVG to React Native Online — Free Tool | getsvgeditor.com",
        "Convert Figma SVG exports to React Native online. Clean design exports for RN — free, no upload.",
        "Figma SVG to React Native", "Figma SVG to RN",
        "Convert a <strong>Figma SVG export</strong> into React Native SVG",
        "Figma SVG to React Native in SVGEditor",
        "Figma SVG to React Native",
        ["Figma SVG to React Native", "Figma export to RN", "Convert Figma SVG RN", "Online Figma SVG RN"],
        "Free online tool to convert Figma SVG exports into React Native components.",
        ["Figma export friendly", "RN conversion", "Live preview", "No upload"],
        "Convert Figma SVG to React Native",
        "Turn a Figma SVG export into React Native SVG output.",
        "Click Convert Figma SVG. RN-ready output is prepared from the export.",
        "Convert Figma SVG", "Convert Figma SVG to React Native",
        [
            ("How do I convert a Figma SVG export to React Native?", "Paste the exported SVG and click Convert Figma SVG to prepare RN output."),
            ("Figma exports often include extra groups — should I clean first?", "Yes. Optimize SVG for React Native helps before converting."),
            ("Need a dedicated Figma export cleanup convert?", "Open Convert Figma SVG Export to React Native."),
            ("Is Figma-to-RN free without uploading?", "Yes. Free browser tool."),
        ],
        "Paste a Figma SVG export. Click Convert Figma SVG.",
    ),
    page(
        "rn", "rn_assets", "convert-figma-svg-export-to-react-native",
        "Convert Figma SVG Export to React Native — Free Tool | getsvgeditor.com",
        "Convert a Figma SVG export to React Native online. Export-oriented cleanup and RN mapping — free, no upload.",
        "Convert Figma SVG Export to React Native", "Figma export to RN",
        "Clean and convert a <strong>Figma SVG export</strong> for React Native",
        "Convert Figma SVG export to React Native in SVGEditor",
        "Convert Figma SVG Export to React Native",
        ["Convert Figma SVG export RN", "Figma SVG export React Native", "Clean Figma SVG for RN", "Online Figma export RN"],
        "Free online tool focused on converting Figma SVG exports into React Native components.",
        ["Export-oriented convert", "RN mapping", "Live preview", "No upload"],
        "Convert a Figma SVG export to React Native",
        "Clean and convert Figma SVG export markup for React Native.",
        "Click Convert Figma export. Export-oriented RN output is prepared.",
        "Convert Figma export", "Convert Figma SVG export to React Native",
        [
            ("How do I convert a Figma SVG export file for React Native?", "Paste the export and click Convert Figma export for cleanup-aware RN output."),
            ("Why a separate tool from Figma SVG to React Native?", "This page targets export cleanup wording; the other is the broad Figma-to-RN entry."),
            ("Illustrations from Figma instead of icons?", "Try SVG Illustration to React Native."),
            ("Does Figma export conversion upload the file?", "No — free, local."),
        ],
        "Paste a Figma SVG export. Click Convert Figma export.",
    ),
    page(
        "rn", "rn_assets", "svg-logo-to-react-native",
        "SVG Logo to React Native Online — Free Tool | getsvgeditor.com",
        "Convert SVG logos to React Native online. Preserve brand marks as RN SVG components — free, no upload.",
        "SVG Logo to React Native", "Logo to RN",
        "Turn a <strong>logo SVG</strong> into a React Native SVG component",
        "SVG logo to React Native in SVGEditor",
        "SVG Logo to React Native",
        ["SVG logo to React Native", "Logo to RN SVG", "Convert logo SVG RN", "Online logo to RN"],
        "Free online tool to convert SVG logos into React Native components.",
        ["Logo-oriented RN output", "Live preview", "Editable source", "No upload"],
        "Convert an SVG logo to React Native",
        "Generate a React Native component from a logo SVG.",
        "Click Convert logo to RN. Logo component output is prepared.",
        "Convert logo to RN", "Convert this SVG logo to React Native",
        [
            ("How do I convert an SVG logo into React Native?", "Paste the logo SVG and click Convert logo to RN."),
            ("Should logos keep viewBox for scaling?", "Yes — pair with SVG to React Native With ViewBox when viewBox is missing."),
            ("Working with a detailed illustration instead of a logo?", "Open SVG Illustration to React Native."),
            ("Is logo-to-RN conversion free?", "Yes. Free browser tool."),
        ],
        "Paste a logo SVG. Click Convert logo to RN.",
    ),
    page(
        "rn", "rn_assets", "svg-illustration-to-react-native",
        "SVG Illustration to React Native Online — Free Tool | getsvgeditor.com",
        "Convert SVG illustrations to React Native online. Handle richer artwork for RN screens — free, no upload.",
        "SVG Illustration to React Native", "Illustration to RN",
        "Convert a richer <strong>illustration SVG</strong> for React Native screens",
        "SVG illustration to React Native in SVGEditor",
        "SVG Illustration to React Native",
        ["SVG illustration to React Native", "Illustration to RN SVG", "Convert illustration SVG RN", "Online illustration RN"],
        "Free online tool to convert SVG illustrations into React Native components.",
        ["Illustration-oriented convert", "Live preview", "Editable markup", "No upload"],
        "Convert an SVG illustration to React Native",
        "Generate React Native SVG output from illustration markup.",
        "Click Convert illustration. Illustration RN output is prepared.",
        "Convert illustration", "Convert SVG illustration to React Native",
        [
            ("How do I convert an SVG illustration for React Native?", "Paste the illustration and click Convert illustration to prepare RN output."),
            ("Illustrations may use unsupported features — what then?", "Run Remove Unsupported SVG for React Native or Remove Unsupported SVG for React Native first."),
            ("Prefer icon-sized assets instead?", "Use SVG Icon to React Native."),
            ("Does illustration conversion upload files?", "No — free, local."),
        ],
        "Paste an illustration SVG. Click Convert illustration.",
    ),
    page(
        "rn", "rn_platform", "svg-to-expo-react-native",
        "SVG to Expo React Native Online — Free Tool | getsvgeditor.com",
        "Convert SVG to Expo React Native online. Expo-friendly react-native-svg components — free, no upload.",
        "SVG to Expo React Native", "SVG to Expo",
        "Prepare SVG for <strong>Expo</strong> React Native projects",
        "SVG to Expo React Native in SVGEditor",
        "SVG to Expo React Native",
        ["SVG to Expo React Native", "Expo SVG from SVG", "Convert SVG Expo RN", "Online SVG to Expo"],
        "Free online tool to convert SVG into Expo-friendly React Native SVG components.",
        ["Expo-oriented RN output", "Live preview", "Editable source", "No upload"],
        "Convert SVG to Expo React Native",
        "Generate Expo-friendly React Native SVG output from SVG.",
        "Click Convert to Expo. Expo-oriented component output is prepared.",
        "Convert to Expo", "Convert SVG to Expo React Native",
        [
            ("How do I convert SVG for an Expo React Native app?", "Paste SVG and click Convert to Expo for Expo-oriented react-native-svg output."),
            ("Do Expo apps still use react-native-svg?", "Yes in most setups — this tool maps toward that workflow."),
            ("Need an Expo SVG component wrapper specifically?", "Open Convert SVG to Expo SVG Component."),
            ("Is Expo conversion free without uploading?", "Yes. Free browser tool."),
        ],
        "Paste SVG. Click Convert to Expo.",
    ),
    page(
        "rn", "rn_platform", "convert-svg-to-expo-svg-component",
        "Convert SVG to Expo SVG Component Online — Free | getsvgeditor.com",
        "Convert SVG to an Expo SVG component online. Component-ready Expo react-native-svg — free browser tool.",
        "Convert SVG to Expo SVG Component", "Expo SVG component",
        "Build an <strong>Expo SVG component</strong> from pasted SVG",
        "Convert SVG to Expo SVG component in SVGEditor",
        "Convert SVG to Expo SVG Component",
        ["Convert SVG to Expo SVG component", "Expo SVG component from SVG", "Expo react-native-svg component", "Online Expo SVG component"],
        "Free online tool to convert SVG into Expo SVG components.",
        ["Expo SVG component shell", "Live preview", "Editable markup", "No upload"],
        "Convert SVG to an Expo SVG component",
        "Generate an Expo-ready SVG component from markup.",
        "Click Make Expo SVG component. Component output is prepared.",
        "Make Expo SVG component", "Convert SVG to Expo SVG component",
        [
            ("How do I make an Expo SVG component from SVG?", "Paste markup and click Make Expo SVG component."),
            ("How is this different from SVG to Expo React Native?", "This page stresses component scaffolding; the other is the broad Expo entry."),
            ("Targeting Android or iOS specifically next?", "See SVG to React Native Android or SVG to React Native iOS."),
            ("Does Expo SVG component conversion upload?", "No — free, local."),
        ],
        "Paste SVG. Click Make Expo SVG component.",
    ),
    page(
        "rn", "rn_platform", "svg-to-react-native-android",
        "SVG to React Native Android Online — Free Tool | getsvgeditor.com",
        "Convert SVG for React Native Android online. Android-friendly RN SVG components — free, no upload.",
        "SVG to React Native Android", "RN Android",
        "Prepare SVG for <strong>React Native Android</strong> rendering",
        "SVG to React Native Android in SVGEditor",
        "SVG to React Native Android",
        ["SVG to React Native Android", "RN Android SVG", "Convert SVG RN Android", "Online SVG RN Android"],
        "Free online tool to convert SVG into React Native components suited for Android.",
        ["Android-oriented RN output", "Live preview", "Editable source", "No upload"],
        "Convert SVG for React Native Android",
        "Generate React Native SVG output with Android usage in mind.",
        "Click Convert for Android. Android-oriented RN output is prepared.",
        "Convert for Android", "Convert SVG for React Native Android",
        [
            ("How do I convert SVG for React Native on Android?", "Paste SVG and click Convert for Android to prepare RN SVG output for Android apps."),
            ("Any Android-specific tip for SVG icons?", "Prefer viewBox-only SVG (no fixed px width/height) so density scales cleanly across Android screens."),
            ("Need iOS-focused conversion instead?", "Open SVG to React Native iOS."),
            ("Is Android RN conversion free?", "Yes. Free browser tool."),
        ],
        "Paste SVG. Click Convert for Android.",
    ),
    page(
        "rn", "rn_platform", "svg-to-react-native-ios",
        "SVG to React Native iOS Online — Free Tool | getsvgeditor.com",
        "Convert SVG for React Native iOS online. iOS-friendly RN SVG components — free browser tool, no upload.",
        "SVG to React Native iOS", "RN iOS",
        "Prepare SVG for <strong>React Native iOS</strong> rendering",
        "SVG to React Native iOS in SVGEditor",
        "SVG to React Native iOS",
        ["SVG to React Native iOS", "RN iOS SVG", "Convert SVG RN iOS", "Online SVG RN iOS"],
        "Free online tool to convert SVG into React Native components suited for iOS.",
        ["iOS-oriented RN output", "Live preview", "Editable markup", "No upload"],
        "Convert SVG for React Native iOS",
        "Generate React Native SVG output with iOS usage in mind.",
        "Click Convert for iOS. iOS-oriented RN output is prepared.",
        "Convert for iOS", "Convert SVG for React Native iOS",
        [
            ("How do I convert SVG for React Native on iOS?", "Paste SVG and click Convert for iOS to prepare RN SVG output for iOS apps."),
            ("Should I remove unsupported SVG features before iOS RN?", "Yes — Remove Unsupported SVG for React Native is a good prep step."),
            ("Building with Expo on iOS?", "Start from SVG to Expo React Native, then verify on device."),
            ("Does iOS RN conversion require uploading?", "No — free, local."),
        ],
        "Paste SVG. Click Convert for iOS.",
    ),
    page(
        "rn", "rn_xml", "svg-to-svgxml-react-native",
        "SVG to SvgXml React Native Online — Free Tool | getsvgeditor.com",
        "Convert SVG to SvgXml for React Native online. Use string-based SvgXml rendering — free, no upload.",
        "SVG to SvgXml React Native", "SvgXml RN",
        "Prepare SVG for <strong>SvgXml</strong> string rendering in React Native",
        "SVG to SvgXml React Native in SVGEditor",
        "SVG to SvgXml React Native",
        ["SVG to SvgXml React Native", "SvgXml from SVG", "RN SvgXml converter", "Online SVG SvgXml"],
        "Free online tool to convert SVG for React Native SvgXml usage.",
        ["SvgXml-oriented output", "Live preview", "Editable source", "No upload"],
        "Convert SVG to SvgXml for React Native",
        "Prepare SVG markup for SvgXml string rendering in RN.",
        "Click Prepare for SvgXml. SvgXml-ready output is prepared.",
        "Prepare for SvgXml", "Prepare SVG for SvgXml React Native",
        [
            ("How do I use SVG with SvgXml in React Native?", "Paste SVG and click Prepare for SvgXml, then pass the string to SvgXml in your app."),
            ("When is SvgXml better than a compiled component?", "SvgXml helps when markup stays dynamic or loads as a string at runtime."),
            ("Need an explicit convert-to-SvgXml wording tool?", "Open SVG to SvgXml React Native."),
            ("Is SvgXml prep free without uploading?", "Yes. Free browser tool."),
        ],
        "Paste SVG. Click Prepare for SvgXml.",
    ),
    page(
        "rn", "rn_xml", "svg-string-to-react-native-component",
        "SVG String to React Native Component Online — Free | getsvgeditor.com",
        "Convert an SVG string to a React Native component online. String-in, component-out — free, no upload.",
        "SVG String to React Native Component", "SVG string to RN",
        "Turn an <strong>SVG string</strong> into a React Native component",
        "SVG string to React Native component in SVGEditor",
        "SVG String to React Native Component",
        ["SVG string to RN component", "String SVG React Native", "Convert SVG string RN", "Online SVG string RN"],
        "Free online tool to convert SVG strings into React Native components.",
        ["String-to-component flow", "Live preview", "Editable source", "No upload"],
        "Convert an SVG string to a React Native component",
        "Generate a React Native component from an SVG string.",
        "Click Convert SVG string. Component output is prepared from the string.",
        "Convert SVG string", "Convert SVG string to React Native component",
        [
            ("How do I convert an SVG string into a React Native component?", "Paste the string and click Convert SVG string to generate a component."),
            ("When should I keep using SvgXml instead of compiling a component?", "Keep SvgXml for truly dynamic strings; compile when the asset is stable."),
            ("Need inline SVG mapped to react-native-svg tags?", "Open Inline SVG to React Native SVG."),
            ("Is SVG-string conversion free?", "Yes. Free browser tool."),
        ],
        "Paste an SVG string. Click Convert SVG string.",
    ),
    page(
        "rn", "rn_xml", "inline-svg-to-react-native-svg",
        "Inline SVG to React Native SVG Online — Free Tool | getsvgeditor.com",
        "Convert inline SVG to react-native-svg online. Map inline markup to RN SVG elements — free, no upload.",
        "Inline SVG to React Native SVG", "Inline SVG to RN",
        "Map <strong>inline SVG</strong> markup to react-native-svg elements",
        "Inline SVG to react-native-svg in SVGEditor",
        "Inline SVG to React Native SVG",
        ["Inline SVG to RN SVG", "Inline SVG react-native-svg", "Convert inline SVG RN", "Online inline SVG RN"],
        "Free online tool to convert inline SVG into react-native-svg markup.",
        ["Inline SVG mapping", "Live preview", "Editable markup", "No upload"],
        "Convert inline SVG to react-native-svg",
        "Transform inline SVG into react-native-svg elements.",
        "Click Convert inline SVG. react-native-svg mapped output is prepared.",
        "Convert inline SVG", "Convert inline SVG to react-native-svg",
        [
            ("How do I convert inline SVG to react-native-svg?", "Paste the inline markup and click Convert inline SVG."),
            ("Is inline SVG different from a full SVG document?", "Inline snippets may omit the root svg wrapper — this tool focuses on that paste style."),
            ("Want SvgXml instead of element mapping?", "Use SVG to SvgXml React Native."),
            ("Does inline conversion require uploading?", "No — free, local."),
        ],
        "Paste inline SVG. Click Convert inline SVG.",
    ),
    page(
        "rn", "rn_elements", "svg-path-to-react-native",
        "SVG Path to React Native Online — Free Tool | getsvgeditor.com",
        "Convert SVG path to React Native online. Map path data to RN Path components — free, no upload.",
        "SVG Path to React Native", "Path to RN",
        "Convert an SVG <strong>path</strong> into React Native SVG",
        "SVG path to React Native in SVGEditor",
        "SVG Path to React Native",
        ["SVG path to React Native", "Path to RN SVG", "Convert path SVG RN", "Online SVG path RN"],
        "Free online tool to convert SVG paths into React Native Path output.",
        ["Path-focused convert", "Live preview", "Editable source", "No upload"],
        "Convert SVG path to React Native",
        "Map SVG path elements to React Native Path components.",
        "Click Convert path to RN. Path-mapped RN output is prepared.",
        "Convert path to RN", "Convert SVG path to React Native",
        [
            ("How do I convert an SVG path to React Native?", "Paste SVG containing path data and click Convert path to RN."),
            ("Need explicit react-native-svg Path element mapping?", "Open Convert SVG Path to React Native SVG Path."),
            ("Converting circles or rects instead?", "See SVG Circle to React Native or SVG Rect to React Native."),
            ("Is path-to-RN free without uploading?", "Yes. Free browser tool."),
        ],
        "Paste SVG with paths. Click Convert path to RN.",
    ),
    page(
        "rn", "rn_elements", "convert-svg-path-to-react-native-svg-path",
        "Convert SVG Path to React Native SVG Path — Free | getsvgeditor.com",
        "Convert SVG path to react-native-svg Path online. Element-accurate Path mapping — free browser tool.",
        "Convert SVG Path to React Native SVG Path", "Path to RN Path",
        "Map <code>path</code> to react-native-svg <strong>Path</strong>",
        "Convert SVG path to react-native-svg Path in SVGEditor",
        "Convert SVG Path to React Native SVG Path",
        ["Convert SVG path to RN Path", "react-native-svg Path from path", "SVG d to RN Path", "Online path to RN Path"],
        "Free online tool to convert SVG path elements into react-native-svg Path components.",
        ["Path → Path mapping", "Live preview", "Editable markup", "No upload"],
        "Convert SVG path to react-native-svg Path",
        "Transform SVG path into a react-native-svg Path element.",
        "Click Convert to RN Path. Path element output is prepared.",
        "Convert to RN Path", "Convert SVG path to react-native-svg Path",
        [
            ("How do I map an SVG path to a react-native-svg Path?", "Paste markup and click Convert to RN Path to map the element and d attribute."),
            ("Does the d attribute stay the same in RN?", "Usually yes — Path still uses d, with RN-friendly prop casing around it."),
            ("Need linearGradient conversion too?", "Open Convert SVG LinearGradient to React Native."),
            ("Does Path mapping upload files?", "No — free, local."),
        ],
        "Paste SVG with a path. Click Convert to RN Path.",
    ),
    page(
        "rn", "rn_elements", "svg-circle-to-react-native",
        "SVG Circle to React Native Online — Free Tool | getsvgeditor.com",
        "Convert SVG circle to React Native online. Map circle elements to RN Circle — free, no upload.",
        "SVG Circle to React Native", "Circle to RN",
        "Convert an SVG <strong>circle</strong> into React Native SVG",
        "SVG circle to React Native in SVGEditor",
        "SVG Circle to React Native",
        ["SVG circle to React Native", "Circle to RN SVG", "Convert circle SVG RN", "Online SVG circle RN"],
        "Free online tool to convert SVG circle elements into React Native Circle output.",
        ["Circle-focused convert", "Live preview", "Editable source", "No upload"],
        "Convert SVG circle to React Native",
        "Map SVG circle elements to React Native Circle components.",
        "Click Convert circle to RN. Circle-mapped RN output is prepared.",
        "Convert circle to RN", "Convert SVG circle to React Native",
        [
            ("How do I convert an SVG circle to React Native?", "Paste SVG with circle elements and click Convert circle to RN."),
            ("Are cx, cy, and r preserved?", "Yes — they map to react-native-svg Circle props."),
            ("Converting rectangles next?", "Use SVG Rect to React Native."),
            ("Is circle-to-RN free?", "Yes. Free browser tool."),
        ],
        "Paste SVG with circles. Click Convert circle to RN.",
    ),
    page(
        "rn", "rn_elements", "svg-rect-to-react-native",
        "SVG Rect to React Native Online — Free Tool | getsvgeditor.com",
        "Convert SVG rect to React Native online. Map rect elements to RN Rect — free browser tool, no upload.",
        "SVG Rect to React Native", "Rect to RN",
        "Convert an SVG <strong>rect</strong> into React Native SVG",
        "SVG rect to React Native in SVGEditor",
        "SVG Rect to React Native",
        ["SVG rect to React Native", "Rect to RN SVG", "Convert rect SVG RN", "Online SVG rect RN"],
        "Free online tool to convert SVG rect elements into React Native Rect output.",
        ["Rect-focused convert", "Live preview", "Editable markup", "No upload"],
        "Convert SVG rect to React Native",
        "Map SVG rect elements to React Native Rect components.",
        "Click Convert rect to RN. Rect-mapped RN output is prepared.",
        "Convert rect to RN", "Convert SVG rect to React Native",
        [
            ("How do I convert an SVG rect to React Native?", "Paste SVG with rect elements and click Convert rect to RN."),
            ("Do rx and ry round corners still work in RN?", "Yes when supported by react-native-svg Rect props — preview after convert."),
            ("Need path conversion instead of rect?", "Open SVG Path to React Native."),
            ("Does rect conversion require uploading?", "No — free, local."),
        ],
        "Paste SVG with rects. Click Convert rect to RN.",
    ),
    page(
        "rn", "rn_elements", "convert-svg-lineargradient-to-react-native",
        "Convert SVG LinearGradient to React Native — Free | getsvgeditor.com",
        "Convert SVG linearGradient to React Native online. Map gradients to RN LinearGradient — free, no upload.",
        "Convert SVG LinearGradient to React Native", "LinearGradient RN",
        "Map <code>linearGradient</code> to react-native-svg <strong>LinearGradient</strong>",
        "Convert SVG linearGradient to React Native in SVGEditor",
        "Convert SVG LinearGradient to React Native",
        ["Convert linearGradient to RN", "RN LinearGradient from SVG", "SVG gradient to RN", "Online linearGradient RN"],
        "Free online tool to convert SVG linearGradient into React Native LinearGradient output.",
        ["LinearGradient mapping", "Live preview", "Editable source", "No upload"],
        "Convert SVG linearGradient to React Native",
        "Transform SVG linearGradient defs into react-native-svg LinearGradient.",
        "Click Convert LinearGradient. RN LinearGradient output is prepared.",
        "Convert LinearGradient", "Convert SVG linearGradient to React Native",
        [
            ("How do I convert SVG linearGradient to React Native?", "Paste SVG with linearGradient defs and click Convert LinearGradient."),
            ("Do stop colors map to Stop components?", "Yes — stops typically become react-native-svg Stop children."),
            ("Gradient looks stretched in layout after convert?", "Check aspect tools like Fix SVG Gradient Stretch in Flexbox on the web SVG first."),
            ("Is LinearGradient conversion free?", "Yes. Free browser tool."),
        ],
        "Paste SVG with linearGradient. Click Convert LinearGradient.",
    ),
    page(
        "rn", "rn_props", "convert-svg-attributes-to-react-native-props",
        "Convert SVG Attributes to React Native Props — Free | getsvgeditor.com",
        "Convert SVG attributes to React Native props online. Map presentation attrs to RN props — free, no upload.",
        "Convert SVG Attributes to React Native Props", "Attrs to RN props",
        "Map SVG <strong>attributes</strong> to React Native component props",
        "Convert SVG attributes to React Native props in SVGEditor",
        "Convert SVG Attributes to React Native Props",
        ["SVG attributes to RN props", "Convert SVG attrs React Native", "RN props from SVG attributes", "Online SVG attrs to RN"],
        "Free online tool to convert SVG attributes into React Native props.",
        ["Attribute → prop mapping", "Live preview", "Editable source", "No upload"],
        "Convert SVG attributes to React Native props",
        "Transform SVG attributes into RN-friendly props.",
        "Click Convert attrs to props. RN prop names update in the output.",
        "Convert attrs to props", "Convert SVG attributes to React Native props",
        [
            ("How do I convert SVG attributes into React Native props?", "Paste SVG and click Convert attrs to props to remap attribute names for RN."),
            ("Is camelCasing part of attribute conversion?", "Often yes — or use CamelCase SVG Attributes for React Native for a dedicated casing pass."),
            ("Need fill remapped to a color prop?", "Open Convert SVG Fill to Color Prop React Native."),
            ("Is attribute-to-prop conversion free?", "Yes. Free browser tool."),
        ],
        "Paste SVG. Click Convert attrs to props.",
    ),
    page(
        "rn", "rn_props", "camelcase-svg-attributes-for-react-native",
        "CamelCase SVG Attributes for React Native Online — Free | getsvgeditor.com",
        "CamelCase SVG attributes for React Native online. Turn stroke-width into strokeWidth and more — free, no upload.",
        "CamelCase SVG Attributes for React Native", "CamelCase attrs",
        "Rewrite SVG attributes into <strong>camelCase</strong> for React Native",
        "CamelCase SVG attributes for React Native in SVGEditor",
        "CamelCase SVG Attributes for React Native",
        ["CamelCase SVG attributes RN", "stroke-width to strokeWidth", "SVG camelCase React Native", "Online camelCase SVG RN"],
        "Free online tool to camelCase SVG attributes for React Native / JSX.",
        ["kebab-case → camelCase", "Live preview", "Editable markup", "No upload"],
        "CamelCase SVG attributes for React Native",
        "Convert hyphenated SVG attributes to camelCase props.",
        "Click CamelCase attributes. Attribute names update for RN/JSX.",
        "CamelCase attributes", "CamelCase SVG attributes for React Native",
        [
            ("How do I camelCase SVG attributes for React Native?", "Paste SVG and click CamelCase attributes to rewrite names like stroke-width to strokeWidth."),
            ("Why does React Native need camelCase?", "JSX props are camelCased; hyphenated SVG attributes are invalid as JS identifiers."),
            ("Want a broader attribute-to-prop conversion?", "Use Convert SVG Attributes to React Native Props."),
            ("Does camelCasing upload my SVG?", "No — free, local."),
        ],
        "Paste SVG with kebab-case attrs. Click CamelCase attributes.",
    ),
    page(
        "rn", "rn_props", "svg-to-react-native-currentcolor",
        "SVG to React Native currentColor Online — Free Tool | getsvgeditor.com",
        "Convert SVG fills to currentColor for React Native online. Theme icons via parent color — free, no upload.",
        "SVG to React Native currentColor", "RN currentColor",
        "Prepare SVG so RN icons follow <strong>currentColor</strong> / parent color",
        "SVG to React Native currentColor in SVGEditor",
        "SVG to React Native currentColor",
        ["SVG to RN currentColor", "currentColor React Native SVG", "Themeable RN SVG icons", "Online RN currentColor SVG"],
        "Free online tool to prepare SVG for currentColor-style theming in React Native.",
        ["currentColor-oriented fills", "Live preview", "Editable source", "No upload"],
        "Prepare SVG for RN currentColor theming",
        "Adjust fills so React Native icons can inherit color.",
        "Click Apply currentColor. Fills update for themeable RN icons.",
        "Apply currentColor", "Apply currentColor for React Native SVG",
        [
            ("How do I make React Native SVG icons use currentColor?", "Paste SVG and click Apply currentColor, then theme via color props in RN."),
            ("Is currentColor exact on all RN versions?", "Behavior can vary — many apps map fill to a color prop instead."),
            ("Prefer an explicit color prop from fill?", "Open Convert SVG Fill to Color Prop React Native."),
            ("Is currentColor prep free?", "Yes. Free browser tool."),
        ],
        "Paste an icon SVG. Click Apply currentColor.",
    ),
    page(
        "rn", "rn_props", "convert-svg-fill-to-color-prop-react-native",
        "Convert SVG Fill to Color Prop React Native — Free | getsvgeditor.com",
        "Convert SVG fill to a React Native color prop online. Drive icon color from props — free browser tool.",
        "Convert SVG Fill to Color Prop React Native", "Fill to color prop",
        "Turn hardcoded <strong>fill</strong> into a React Native <code>color</code> prop",
        "Convert SVG fill to color prop React Native in SVGEditor",
        "Convert SVG Fill to Color Prop React Native",
        ["SVG fill to RN color prop", "Convert fill color prop RN", "RN icon color from fill", "Online fill to color RN"],
        "Free online tool to convert SVG fill attributes into React Native color props.",
        ["fill → color prop", "Live preview", "Editable markup", "No upload"],
        "Convert SVG fill to an RN color prop",
        "Rewrite fills so color can be passed as a React Native prop.",
        "Click Fill to color prop. Color-prop-ready output is prepared.",
        "Fill to color prop", "Convert SVG fill to React Native color prop",
        [
            ("How do I convert SVG fill into a React Native color prop?", "Paste SVG and click Fill to color prop to prepare prop-driven coloring."),
            ("Should I use currentColor instead of a color prop?", "currentColor suits web-like inheritance; color props are clearer in many RN icon APIs."),
            ("Need size props alongside color?", "Continue with SVG Icon With Size Props React Native."),
            ("Does fill-to-color conversion upload?", "No — free, local."),
        ],
        "Paste SVG with fills. Click Fill to color prop.",
    ),
    page(
        "rn", "rn_props", "svg-icon-with-size-props-react-native",
        "SVG Icon With Size Props React Native Online — Free | getsvgeditor.com",
        "Add size props to React Native SVG icons online. width/height props for RN icons — free, no upload.",
        "SVG Icon With Size Props React Native", "RN size props",
        "Expose <strong>width/height size props</strong> on an RN SVG icon",
        "SVG icon with size props React Native in SVGEditor",
        "SVG Icon With Size Props React Native",
        ["RN SVG icon size props", "width height props RN SVG", "Sized React Native icon", "Online RN icon size props"],
        "Free online tool to prepare React Native SVG icons with size props.",
        ["width/height props", "Icon-oriented output", "Live preview", "No upload"],
        "Add size props to an RN SVG icon",
        "Prepare an SVG icon component that accepts width and height props.",
        "Click Add size props. Size-prop-ready icon output is prepared.",
        "Add size props", "Add size props to React Native SVG icon",
        [
            ("How do I give a React Native SVG icon size props?", "Paste the icon and click Add size props to prepare width/height prop wiring."),
            ("Should the icon keep a viewBox when sizing via props?", "Yes — viewBox keeps aspect while props control rendered size."),
            ("Want a responsive icon that scales with layout?", "Open Responsive SVG Icon React Native Component."),
            ("Is size-props prep free?", "Yes. Free browser tool."),
        ],
        "Paste an icon SVG. Click Add size props.",
    ),
    page(
        "rn", "rn_props", "responsive-svg-icon-react-native-component",
        "Responsive SVG Icon React Native Component — Free | getsvgeditor.com",
        "Build a responsive SVG icon React Native component online. Fluid icon sizing for RN layouts — free, no upload.",
        "Responsive SVG Icon React Native Component", "Responsive RN icon",
        "Create a <strong>responsive</strong> React Native SVG icon component",
        "Responsive SVG icon React Native component in SVGEditor",
        "Responsive SVG Icon React Native Component",
        ["Responsive RN SVG icon", "Fluid React Native icon", "Responsive SVG RN component", "Online responsive RN icon"],
        "Free online tool to build responsive React Native SVG icon components.",
        ["Responsive icon sizing", "RN component output", "Live preview", "No upload"],
        "Build a responsive RN SVG icon component",
        "Prepare an SVG icon component that scales with layout.",
        "Click Make responsive RN icon. Responsive icon output is prepared.",
        "Make responsive RN icon", "Make responsive React Native SVG icon component",
        [
            ("How do I make a responsive React Native SVG icon component?", "Paste SVG and click Make responsive RN icon to prepare fluid sizing."),
            ("Is this different from fixed size props?", "Size props set explicit dimensions; responsive icons adapt to parent layout constraints."),
            ("Need viewBox preserved for responsive scaling?", "Use SVG to React Native With ViewBox first if viewBox is missing."),
            ("Does responsive icon conversion upload?", "No — free, local."),
        ],
        "Paste an icon SVG. Click Make responsive RN icon.",
    ),
    page(
        "rn", "rn_props", "svg-to-react-native-with-viewbox",
        "SVG to React Native With ViewBox Online — Free Tool | getsvgeditor.com",
        "Convert SVG to React Native while preserving viewBox online. Keep aspect-safe RN SVG — free, no upload.",
        "SVG to React Native With ViewBox", "RN with viewBox",
        "Convert to RN while keeping a correct <strong>viewBox</strong>",
        "SVG to React Native with viewBox in SVGEditor",
        "SVG to React Native With ViewBox",
        ["SVG to RN with viewBox", "Preserve viewBox React Native", "RN SVG viewBox convert", "Online RN viewBox SVG"],
        "Free online tool to convert SVG to React Native while preserving viewBox.",
        ["viewBox-preserving convert", "Live preview", "Editable markup", "No upload"],
        "Convert SVG to React Native with viewBox",
        "Generate RN SVG output that keeps a correct viewBox.",
        "Click Convert with viewBox. RN output keeps viewBox framing.",
        "Convert with viewBox", "Convert SVG to React Native with viewBox",
        [
            ("How do I convert SVG to React Native without losing viewBox?", "Paste SVG and click Convert with viewBox so framing stays intact."),
            ("Why is viewBox important in RN SVG?", "It preserves aspect ratio when width/height props change."),
            ("Need size props after keeping viewBox?", "Continue with SVG Icon With Size Props React Native."),
            ("Is viewBox-preserving convert free?", "Yes. Free browser tool."),
        ],
        "Paste SVG. Click Convert with viewBox.",
    ),
    page(
        "rn", "rn_clean", "optimize-svg-for-react-native",
        "Optimize SVG for React Native Online — Free Tool | getsvgeditor.com",
        "Optimize SVG for React Native online. Slim markup before RN conversion — free browser tool, no upload.",
        "Optimize SVG for React Native", "Optimize for RN",
        "<strong>Optimize</strong> SVG markup so it converts cleanly to React Native",
        "Optimize SVG for React Native in SVGEditor",
        "Optimize SVG for React Native",
        ["Optimize SVG for React Native", "RN SVG optimize", "Slim SVG for RN", "Online optimize SVG RN"],
        "Free online tool to optimize SVG for React Native conversion.",
        ["RN-oriented optimize", "Live preview", "Editable source", "No upload"],
        "Optimize SVG for React Native",
        "Reduce and tidy SVG so React Native conversion is cleaner.",
        "Click Optimize for RN. Optimized markup is prepared.",
        "Optimize for RN", "Optimize SVG for React Native",
        [
            ("How do I optimize SVG before React Native conversion?", "Paste SVG and click Optimize for RN to slim markup for RN pipelines."),
            ("Is optimize different from remove-unsupported?", "Optimize tidies structure/size; Remove Unsupported SVG for React Native drops RN-hostile nodes."),
            ("Need to drop scripts and foreignObject before convert?", "Open Remove Unsupported SVG for React Native."),
            ("Is RN optimize free without uploading?", "Yes. Free browser tool."),
        ],
        "Paste SVG. Click Optimize for RN.",
    ),
    page(
        "rn", "rn_clean", "remove-unsupported-svg-for-react-native",
        "Remove Unsupported SVG for React Native Online — Free | getsvgeditor.com",
        "Remove unsupported SVG features for React Native online. Drop elements RN SVG cannot render — free, no upload.",
        "Remove Unsupported SVG for React Native", "Remove unsupported",
        "Remove SVG features <strong>unsupported</strong> by React Native SVG",
        "Remove unsupported SVG for React Native in SVGEditor",
        "Remove Unsupported SVG for React Native",
        ["Remove unsupported SVG RN", "Unsupported SVG React Native", "Strip unsupported RN SVG", "Online remove unsupported RN"],
        "Free online tool to remove unsupported SVG features before React Native conversion.",
        ["Strip unsupported features", "Live preview", "Editable markup", "No upload"],
        "Remove unsupported SVG for React Native",
        "Drop SVG features that react-native-svg typically cannot render.",
        "Click Remove unsupported. Unsupported features are stripped.",
        "Remove unsupported", "Remove unsupported SVG for React Native",
        [
            ("How do I remove unsupported SVG features for React Native?", "Paste markup and click Remove unsupported to strip features RN SVG often rejects."),
            ("What kinds of features get removed?", "Commonly filters, foreignObject, scripts, and other web-only constructs — preview the result."),
            ("Need a general tidy pass afterward?", "Open Optimize SVG for React Native."),
            ("Does unsupported removal upload files?", "No — free, local."),
        ],
        "Paste SVG. Click Remove unsupported.",
    ),
    page(
        "rn", "rn_clean", "svgr-native-svg-to-react-native-online",
        "SVGR Native SVG to React Native Online — Free Tool | getsvgeditor.com",
        "Convert SVG with SVGR Native style online for React Native. SVGR Native-oriented output — free, no upload.",
        "SVGR Native SVG to React Native Online", "SVGR Native online",
        "Prepare SVG using an <strong>SVGR Native</strong>-oriented React Native flow",
        "SVGR Native SVG to React Native online in SVGEditor",
        "SVGR Native SVG to React Native Online",
        ["SVGR Native to React Native", "SVGR Native SVG online", "SVGR Native RN converter", "Online SVGR Native SVG"],
        "Free online tool for SVGR Native-oriented SVG to React Native conversion.",
        ["SVGR Native-oriented flow", "Live preview", "Editable source", "No upload"],
        "Convert with SVGR Native-oriented RN output",
        "Prepare SVG for an SVGR Native-style React Native component.",
        "Click SVGR Native convert. SVGR Native-oriented output is prepared.",
        "SVGR Native convert", "Convert SVG with SVGR Native for React Native",
        [
            ("How do I convert SVG with an SVGR Native-oriented flow online?", "Paste SVG and click SVGR Native convert to prepare RN-oriented component output."),
            ("How does this relate to Optimize SVG for React Native?", "Optimize is a prep cleanup; this page is the SVGR Native-oriented conversion entry."),
            ("Should I optimize before SVGR Native?", "Yes — Optimize SVG for React Native is a good prep step."),
            ("Is SVGR Native conversion free?", "Yes. Free browser tool."),
        ],
        "Paste SVG. Click SVGR Native convert.",
    ),
    page(
        "rn", "rn_hub", "svg-to-react-native-functional-component",
        "SVG to React Native Functional Component — Free Tool | getsvgeditor.com",
        "Convert SVG to a React Native functional component online. function/FC style RN SVG — free, no upload.",
        "SVG to React Native Functional Component", "RN functional",
        "Emit a <strong>functional component</strong> wrapping react-native-svg",
        "SVG to React Native functional component in SVGEditor",
        "SVG to React Native Functional Component",
        ["SVG to RN functional component", "Functional React Native SVG", "RN FC from SVG", "Online RN functional SVG"],
        "Free online tool to convert SVG into a React Native functional component.",
        ["Functional component output", "Live preview", "Editable source", "No upload"],
        "Convert SVG to a React Native functional component",
        "Generate a functional React Native SVG component from SVG.",
        "Click Make functional component. Functional component output is prepared.",
        "Make functional component", "Convert SVG to React Native functional component",
        [
            ("How do I convert SVG into a React Native functional component?", "Paste SVG and click Make functional component to generate a function-style RN SVG component."),
            ("When should I use forwardRef instead of a plain function?", "Use forwardRef when parent code must attach a ref for layout or animation."),
            ("Need a broader SVG React Native Component Generator flow?", "Open SVG React Native Component Generator."),
            ("Is functional-component conversion free?", "Yes. Free browser tool."),
        ],
        "Paste SVG. Click Make functional component.",
    ),
    page(
        "rn", "rn_hub", "svg-to-react-native-forwardref-component",
        "SVG to React Native forwardRef Component — Free Tool | getsvgeditor.com",
        "Convert SVG to a React Native forwardRef component online. Ref-friendly RN SVG wrappers — free, no upload.",
        "SVG to React Native forwardRef Component", "RN forwardRef",
        "Wrap SVG in a <strong>forwardRef</strong> React Native component",
        "SVG to React Native forwardRef component in SVGEditor",
        "SVG to React Native forwardRef Component",
        ["SVG to RN forwardRef", "forwardRef React Native SVG", "RN ref SVG component", "Online RN forwardRef SVG"],
        "Free online tool to convert SVG into a React Native forwardRef component.",
        ["forwardRef component output", "Live preview", "Editable markup", "No upload"],
        "Convert SVG to a React Native forwardRef component",
        "Generate a forwardRef React Native SVG component from SVG.",
        "Click Make forwardRef component. forwardRef component output is prepared.",
        "Make forwardRef component", "Convert SVG to React Native forwardRef component",
        [
            ("How do I convert SVG into a React Native forwardRef component?", "Paste SVG and click Make forwardRef component to generate a ref-forwarding wrapper."),
            ("Why use forwardRef for SVG icons?", "Parents can measure, animate, or focus the underlying native view when refs are forwarded."),
            ("Prefer a plain functional component without refs?", "Use SVG to React Native Functional Component."),
            ("Does forwardRef conversion require uploading?", "No — free, local."),
        ],
        "Paste SVG. Click Make forwardRef component.",
    ),
]


def main():
    assert len(PAGES) == 47, f"expected 62 pages, got {len(PAGES)}"
    questions = [q for p in PAGES for q, _ in p["faqs"]]
    dups = sorted({q for q in questions if questions.count(q) > 1})
    assert len(questions) == len(set(questions)), f"duplicate FAQ questions: {dups}"
    for p in PAGES:
        assert len(p["faqs"]) == 4, p["slug"]
        assert p["note_html"], p["slug"]
        assert 2 <= len(p["guides"]) <= 4, (p["slug"], len(p["guides"]))
        build_page(p)
    slugs_path = Path(__file__).resolve().parent / "_asr_slugs.txt"
    slugs_path.write_text("\n".join(p["slug"] for p in PAGES) + "\n", encoding="utf-8")
    print("wrote", slugs_path)
    print("done", len(PAGES))


if __name__ == "__main__":
    main()
